### PR TITLE
Add OpenStack testing (via ssh) to travis ci

### PR DESCRIPTION
**Pull request by sehqlr**
We need to be able to run CI against OpenStack. This approach uses ssh
to run the testing commands from a jump host maintained by Cisco Cloud.
It requires the secret env vars OS_IP and OS_KEY, which are the IP
address of the jump box, and an ssh private key, respectively. It also
requires the creation of a travis user on the jump host.

Most of the changes here are if/thens for whether we need to test
against OpenStack or not. My hope is that when we switch our deployments
to a container, this will simplify things in this file also. Right now,
it feels a bit hacky.

As part of these changes, I altered the semantics of the cleanup script:
instead of calling terraform in two lines, we will use the builtin
`travis_retry` command. It will attempt the destroy 3 times, which
should be more than enough retries for the terraform AWS bug.

### CODE REVIEW

**Comment by siddharthist** [comment]
:open_mouth: This is awesome. Great work @sehqlr!

**Comment by siddharthist** [comment]
Unfortunately, all the build errored :cry:

**Comment by siddharthist** [comment]
@sehqlr Could we generate an SSH key without a passphrase?

**Comment by sehqlr** [comment]
@siddharthist The only way to do that is setting the passphrase to an empty string, which I have done. The problem is that `ssh-add` opens a TTY when it runs, which I found out after that last commit. Most of the advice that I found online was to use `expect`, but I'm thinking that the `before_script` section is getting far too complex, and should be rolled into a separate script.

The work I'm doing towards a docker-based deploy ties into this as well, but a big chunk of work that I've done isn't ready to be pushed yet.

**Comment by siddharthist** [comment]
@sehqlr Should we close in favor of the new Docker process that will replace it?

**Comment by sehqlr** [comment]
Closing

**Pull request closed without merging**
