### PR TITLE
mesos: refactor logging

### LINKED ISSUE #764: mesos logrotation issues
Post-rotation, new logs are being written to the archive directory `/var/log/mesos/archive`. We need to review our configuration - there does appear to be some issues with using logrotate and mesos: https://issues.apache.org/jira/browse/MESOS-1375

### PR DESCRIPTION
**Pull request by ryane**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes (n/a)

- don't use MESOS_LOG_DIR
- stdout/stderr is logged to journal
- rsyslog sends mesos-master and mesos-agent logs to files
- updated logrotate config
- updated logstash rules

Fixes #764

### CODE REVIEW

**Comment by ryane** [comment]
@sehqlr ready for testing

**Comment by BrianHicks** [comment]
:clap: this looks pretty great!

**Comment by sehqlr** [comment]
testing it now

**Comment by sehqlr** [comment]
We are a go on this one.

**Pull request merged**
