### PR TITLE
remove consul_dns_domain

### PR DESCRIPTION
**Pull request by siddharthist**
- [x] Installs cleanly on a fresh build of most recent master branch
- [ ] DOES NOT upgrade cleanly from the most recent release
- [x] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by siddharthist** [comment]
Two test failures on `dnsmasq` checks, one on a `docker pull`. Pretty sure they're all unrelated.

**Comment by sehqlr** [comment]
Do we know what the upgrade path will be on this?

**Comment by siddharthist** [comment]
@sehqlr I think it requires you to change your `consul_dns_domain`. It might actually upgrade cleanly, since consul gets reloaded after it's reconfigured.

**Comment by BCWilsonDotCom** [comment]
Just curious, what's the reason for hardcoding .consul as the consul dns domain?

**Comment by siddharthist** [comment]
@BCWilsonDotCom It simplifies our packaging configuration, all of our packages can assume a `.consul` domain. Plus, it didn't seem like anyone was using this, so it's one fewer moving part.

**Comment by stevendborrelli** [comment]
I think with the new mantl-dns settings in dnsmasq, we don't even need to use .consul at all. 

We should be able to do lookups like:
hostname
hostname.node
hostname.node.dc

servicename.service
servicename.service.dc

**Comment by siddharthist** [comment]
Closing this, we should implement @stevendborrelli's solution.

**Pull request closed without merging**
