### PR TITLE
Terraform host name updates

### PR DESCRIPTION
**Pull request by johnswil**
Hi, thank you for your contribution to Mantl! Before we can accept any code into
master, we need it to meet the following criteria. If there are any you can't
satisfy yourself, go ahead and open the pull request anyway and we'll help you
test. Feel free to delete this message once you're done. Thanks again!

- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by johnswil** [comment]
Terraform host name updates

**Comment by siddharthist** [comment]
@johnswil I don't immediately see why this should be part of the public documentation, especially with what look like real IP addresses and hostnames. Could you elaborate on the motivation?

**Comment by johnswil** [comment]
Agreed, this should not include real IP addresses, I’ll re commit.

Thank you

**Comment by siddharthist** [comment]
@johnswil Why do we want to update the hostnames at all?

**Comment by johnswil** [comment]
The hostname example needs to reflect current tooling ie. Kubernetes and Traefik

**Comment by siddharthist** [comment]
@johnswil Good thinking. Could you just add `kubeworker` nodes, rather than changing all the hostnames? We also don't have roles for `infra` and `drone`, so I think it might be best not to add them here.

**Comment by johnswil** [comment]
Agreed, I’ll re-commit soon

**Comment by johnswil** [comment]
closed due to duplicate

**Pull request closed without merging**
