### PR TITLE
Added conditional task for GCE

### PR DESCRIPTION
**Pull request by lowwalker**
GCE centos instances don't have yum-utils installed by default. I've added a task to install them based on provider, otherwise the timeout increase task will fail.

### CODE REVIEW

**Comment by lowwalker** [comment]
This doesn't fail when actually using GCE, those builds are false errors!

**Comment by siddharthist** [comment]
@lowwalker Sorry, those erronious failures will be fixed with #1245

**Comment by siddharthist** [comment]
I've also seen this on DigitalOcean, would you mind changing this to mirror https://github.com/CiscoCloud/mantl/pull/1250?

**Comment by siddharthist** [comment]
This is already in the common role: https://github.com/CiscoCloud/mantl/blob/master/roles/common/tasks/main.yml#L21-L27. We should figure out why that's not working. It also doesn't seem to be a provider-specific issue. Thanks for pointing this out @lowwalker!

**Comment by siddharthist** [comment]
It was added in https://github.com/CiscoCloud/mantl/blob/master/roles/common/tasks/main.yml#L21-L27

**Pull request closed without merging**
