### PR TITLE
travis: terraform plan CLC and Softlayer

### LINKED ISSUE #1528: Use `plan` or `graph` to lint all of our supported terraform providers
This is an issue that @siddharthist asked me to post.

For CI testing, it would be *really* nice to verify terraform configs for all of our providers, rather than just AWS, DO, and GCE. We can use either `plan` (or possibly `graph`) to verify sane configs without actually provisioning them.

### PR DESCRIPTION
**Pull request by siddharthist**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

Don't merge, this is waiting on a good CI build.  

This PR:
 * runs `terraform plan` on providers that we don't already test
 * removes some unnecessary vars, `MANTL_CI_FORK_CHECK` and `ARE_SECRETS_AVAILABLE`, both of which can be deduced from `DOCKER_SECRETS`
 * switches from sam's docker image to one built from #1537
 * fixes #1528, #1557

### CODE REVIEW

**Comment by siddharthist** [comment]
So it looks like there are some supported providers that aren't configured in the mantl-testing docker container right now:
```
* clc_server.node: provider clc couldn't be found
* clc_public_ip.ip: provider clc couldn't be found
```
```
* softlayer_ssh_key.default: provider softlayer couldn't be found
```
```
* triton_machine.instance: provider triton couldn't be found
```
```
Errors:
  * vsphere_virtual_machine.mi-edge-nodes #0: disk.0: invalid or unknown key: type
  * vsphere_virtual_machine.mi-edge-nodes #0: : invalid or unknown key: linked_clone
  * vsphere_virtual_machine.mi-control-nodes #2: disk.0: invalid or unknown key: type
  * vsphere_virtual_machine.mi-control-nodes #2: : invalid or unknown key: linked_clone
  * vsphere_virtual_machine.mi-worker-nodes #1: disk.0: invalid or unknown key: type
  * vsphere_virtual_machine.mi-worker-nodes #1: : invalid or unknown key: linked_clone
  * vsphere_virtual_machine.mi-control-nodes #0: disk.0: invalid or unknown key: type
  * vsphere_virtual_machine.mi-control-nodes #0: : invalid or unknown key: linked_clone
  * vsphere_virtual_machine.mi-worker-nodes #0: disk.0: invalid or unknown key: type
  * vsphere_virtual_machine.mi-worker-nodes #0: : invalid or unknown key: linked_clone
[...]
```
I think some/most of these errors could be fixed up [upgrading to Terraform v0.6.16](https://github.com/hashicorp/terraform/issues/1406). Where is the testing Docker image built @sehqlr?

**Comment by siddharthist** [comment]
Not sure why that last build is failing. Ah well, that's a problem for me on Monday :grimacing:

**Comment by sehqlr** [comment]
Well… I’ve been using my own docker hub repo, actually.

**Comment by siddharthist** [comment]
Good news: We're going to actually test with CLC, not just lint it :smile: 

Bad news: vsphere requires a valid server to even `terraform get`, so we won't be able to lint it. I've removed it from the pr

Mixed news: Found a real bug in the softlayer config! #1557

**Comment by siddharthist** [comment]
@sehqlr This is ready for your review!

**Comment by sehqlr** [comment]
Not only is this Looks Good To Me, it Looks Awesome To Me! I really appreciate the cleanup work done here :blush:

**Pull request merged**
