### PR TITLE
Refactor DigitalOcean terraform configs into modules

### LINKED ISSUE #1707: Refactor DigitalOcean Terraform configurations
They should be in modules, like AWS, GCE, or Triton. This will make it easier to add the new disk storage!

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

### PR DESCRIPTION
**Pull request by siddharthist**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

fixes #1707

### CODE REVIEW

**Comment by siddharthist** [comment]
Build passed on DigitalOcean!

**Comment by siddharthist** [comment]
fixed merge conflict

**Comment by siddharthist** [comment]
Build still passes on DigitalOcean

**Comment by sehqlr** [comment]
I testing this manually too. LGTM

**Comment by siddharthist** [comment]
Thanks @sehqlr!

**Pull request merged**
