### PR TITLE
patch use builtin vsphere provider

### PR DESCRIPTION
**Pull request by nitgithub**
Works against ESXi 6.0, template needs to have the latest VMware tools installed, or else the customization will not work.

- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by siddharthist** [comment]
cc @mikelovecnm

**Comment by siddharthist** [comment]
cc @chrislovecnm

**Comment by chrislovecnm** [comment]
Changes look fine. I left a comment on the docs. Part of the docs may be referring to a bug that exists in the provider. The provider is not waiting for vsphere to provision the ip addresses.

**Comment by nitgithub** [comment]
Seems the issue is in [/builtin/providers/vsphere/resource_vsphere_virtual_machine.go](https://github.com/hashicorp/terraform/blob/master/builtin/providers/vsphere/resource_vsphere_virtual_machine.go#L477). Guest.Net is of type GuestNicInfo which gets filled in with the [vmware/govmomi/list/lister.go](https://github.com/vmware/govmomi/blob/master/list/lister.go#L130)

**Comment by siddharthist** [comment]
Sweet, thanks to both of you for the PR and the review!

**Pull request merged**
