### PR TITLE
consul: apply rolling restart only to server nodes

### PR DESCRIPTION
**Pull request by abn**
- Fix typo in `consul-rolling-restart.sh` script
- Proposing the introduction of `watch_timeout` as optional second argument, defaulting to 60 (seconds)
- For non-leaders, if restart key is not seen for `watch_timeout` seconds, force a restart

Not sure if `consul-cli kv-delete ${ccargs} secure/${ip}/restart restart` should be performed for good measure after `wait_for_upness ${node}` completes for the node.

@ChrisAubuchon thoughts? I am fairly certain I might have missed something obvious here.

### CODE REVIEW

**Comment by ChrisAubuchon** [comment]
I don't think the non-leaders should restart after a timeout. The point of `consul-rolling-restart.sh` is to ensure that only one Consul node is down at any given time. This is to avoid losing Consul quorum which will require manual clearing of Consul peers. With a timeout all of the non-leader nodes can possibly restart simultaneously and cause a loss of quorum.

It won't hurt anything to have a `kv-delete` after `wait_for_upness` completes. It *shouldn't* have any effect since the key should have already been deleted by the restarting node.

**Comment by abn** [comment]
Agreed, that this introduces a risk. Any thoughts on a viable solution for the case where the play is limited to, for instance, only `role=worker`? In this scenario the workers would wait for ever if `restart consul` is notified. Some mechanism to conditionally perform serial restarts when no servers are present?

**Comment by ChrisAubuchon** [comment]
A couple of ideas.

1. A separate handler for non-rolling restarts. For nodes in the `role=worker` group, rolling restarts aren't required.
2. Add command line options of `consul-rolling-restart.sh` to restart consul node types. Something like `consul-rolling-restart.sh --clients --servers`

**Comment by abn** [comment]
@ChrisAubuchon have attempted to make the client/server detection transparent. Let me know if that works.

**Comment by siddharthist** [comment]
@abn @ChrisAubuchon How's this going?

**Comment by ChrisAubuchon** [comment]
This was fixed in https://github.com/CiscoCloud/mantl/commit/6d750ac3e1b6e8a91802bd7f7dc3768a333d7015

**Pull request closed without merging**
