### PR TITLE
Feature/mesos attributes

### PR DESCRIPTION
**Pull request by stevendborrelli**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by siddharthist** [comment]
How can we tell whether or not this works (i.e. where are Mesos agent attributes visible)?

**Comment by stevendborrelli** [comment]
@siddharthist you want to look at the mesos /etc/sysconfig/mesos-agent files. 

To test, put this in your role=worker stanza in sample.yml:

```
- hosts: role=worker
  # role=worker hosts are a subset of "all". Since we already gathered facts on
  # all servers, we can skip it here to speed up the deployment.
  gather_facts: no
  vars:
    consul_dns_domain: consul
    mesos_mode: follower
   mesos_attributes:
      - "node_id:{{ inventory_hostname }}"
      - "type:infra"
```

**Comment by siddharthist** [comment]
rebased, will test soon.

**Comment by siddharthist** [comment]
LGTM :+1: 
```
$ cat sample.yml
---
# CHECK SECURITY - when customizing you should leave this in. If you
# take it out and forget to specify security.yml, security could be turned off
# on components in your cluster!
- include: "{{ playbook_dir }}/playbooks/check-requirements.yml"

# The worker role itself has a minimal configuration, as it's designed mainly to
# run software that the Mesos leader shedules. It also forwards traffic to
# globally known ports configured through Marathon.
- hosts: role=worker
  # role=worker hosts are a subset of "all". Since we already gathered facts on
  # all servers, we can skip it here to speed up the deployment.
  gather_facts: no
  vars:
    mesos_mode: follower
    consul_dns_domain: consul
    mesos_mode: follower
    mesos_attributes:
      - "node_id:{{ inventory_hostname }}"
      - "type:infra"
  roles:
    - mesos
```
```
$ ssh centos@52.38.117.163
Last login: Fri Apr  8 01:05:09 2016 from c135h054.wless.reed.edu
[centos@ip-10-1-1-21 ~]$ cat /etc/sysconfig/mesos-agent
# common configuration
MESOS_PORT=5051
MESOS_ADVERTISE_IP=10.1.1.21
MESOS_IP=10.1.1.21
MESOS_HOSTNAME=lb0-worker-01.node.consul
MESOS_EXTERNAL_LOG_FILE=/var/log/mesos/mesos-agent.log
MESOS_LOGGING_LEVEL=WARNING

# agent configuration

# required
MESOS_MASTER=zk://mesos:8TsHoET0m4lsxyOz@zookeeper.service.consul:2181/mesos

# optional
MESOS_ATTRIBUTES=node_id:lb0-worker-01;type:infra
MESOS_RESOURCES=ports(*):[4000-5000, 7000-8000, 9000-10000, 25000-26000, 31000-32000]
MESOS_CONTAINERIZERS=docker,mesos
MESOS_EXECUTOR_REGISTRATION_TIMEOUT=10mins
MESOS_WORK_DIR=/var/lib/mesos

# authentication
MESOS_CREDENTIAL=file:///etc/sysconfig/mesos-agent-credential

EXTRA_OPTS=""
```

**Comment by stevendborrelli** [comment]
So you had to run it twice to make it work? The main issue here is that if an attribute changes, we need to remove the mesos meta file.

**Comment by siddharthist** [comment]
No, I wasn't able to get this branch working.

**Comment by stevendborrelli** [comment]
The newest commits fix the issue. We now correctly clear out agent metadata based on the configured mesos_work_dir.

**Pull request merged**
