### PR TITLE
Move addon-specific roles to addons/roles

### LINKED ISSUE #1166: Configure roles_path for addons to be addons/roles
Having our addons in `roles/` clutters the directory. We should move them to `addons/roles` and set the [`roles_path` variable](http://docs.ansible.com/ansible/intro_configuration.html#roles-path) variable accordingly in ansible.cfg.

### PR DESCRIPTION
**Pull request by siddharthist**
Fixes #1166. Should include
 - [x] logstash
 - [x] chronos
 - [x] elk
 - [x] collectd
 - [x] glusterfs
 - [x] iptables
 - [x] kafka
 - [ ] docker swarm

### CODE REVIEW

**Comment by siddharthist** [comment]
This is waiting for Chronos to be moved to an addon

**Comment by sehqlr** [comment]
The collectd blocker was merged, but the kafka blocker is still open

**Comment by siddharthist** [comment]
Rebased and completed, ready to test. Just need to build a Mantl cluster and install a few addons.

**Comment by siddharthist** [comment]
This will probably break some `include_vars` statements, we should wait until we resolve #1319

**Comment by siddharthist** [comment]
Closing until resolution of #1319

**Pull request closed without merging**
