### PR TITLE
elasticsearch and kibana uis in mantlui

### LINKED ISSUE #1131: configure kibana index pattern by default
Currently, Kibana prompts you to configure an index pattern the first time you load it. It would be nice if we could automate this as part of the ELK addon setup.

### LINKED ISSUE #1135: Elasticsearch framework UI in MantlUI
When it is installed, the elasticsearch framework ui should be available from Mantl UI.

### LINKED ISSUE #1136: Kibana UI in MantlUI
When it is installed, the Kibana ui should be available from Mantl UI.

### PR DESCRIPTION
**Pull request by ryane**
* Elasticsearch and Kibana UIs are available in Mantl UI when installed
* Kibana index search pattern created by default
* Chronos and Traefik services will not appear in Mantl UI if they are not installed

Fixes #1136 
Fixes  #1135 
Fixes #1131

### CODE REVIEW

**Comment by siddharthist** [comment]
I'll test today. What clouds have you tested on @ryane?

**Comment by ryane** [comment]
thanks! GCE so far.

To test, after installing the elk add-on, you should see the elasticsearch and kibana links show up in Mantl UI and the UIs should be accessible. Note that it can take a few minutes for the services to fully launch and become healthy. When you access the Kibana UI, it should not prompt you to create an index search pattern - it should just load the Discover tab.

**Comment by siddharthist** [comment]
:+1: on DigitalOcean!
screenshot

**Comment by anners** [comment]
:+1: on AWS
screen shot 2016-02-26 at 3 58 23 pm

**Pull request merged**
