### PR TITLE
traefik: package version 1.0.0

### PR DESCRIPTION
**Pull request by ryane**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

an updated package is forthcoming but this is needed so that master is not broken

### CODE REVIEW

**Comment by npateriya** [comment]
@stevendborrelli @ryane  FYI: We have found this blocker in upgrading to latest traefik https://github.com/containous/traefik/issues/462

**Comment by distributorofpain** [comment]
The issue @npateriya brought has been resolved in a newer build.  Next steps?  Seems i need an upgraded traefik install to fix a host header forward issue :smile:

**Comment by ryane** [comment]
if you build from master or 1.2 (or use the mantl-1.2 repo), you will get traefik 1.0 which was released a few days ago and does include https://github.com/containous/traefik/issues/462.

**Comment by distributorofpain** [comment]
Well i tried to manually update traefik via yum, but then i ran into #1563 .  I was trying to avoid rebuilding the entire environment as i would have to add back all the applications( i have 50 or so running in test ). 

Course Yum doenst have the latest build...

**Pull request merged**
