### PR TITLE
Expose Kubernetes dashboard in Mantl UI

### PR DESCRIPTION
**Pull request by BrianHicks**
- [X] Installs cleanly on a fresh build of most recent master branch
- [X] Upgrades cleanly from the most recent release
- [X] Updates documentation relevant to the changes

This exposes the Kubernetes dashboard in Mantl UI. It depends on https://github.com/CiscoCloud/nginx-mantlui/pull/17 being accepted and a new container pushed.

### CODE REVIEW

**Comment by siddharthist** [comment]
Can we get an update here when the new container is pushed @BrianHicks @ryane?

**Comment by siddharthist** [comment]
How does one install the UI?

**Comment by siddharthist** [comment]
I couldn't get the UI to show up in Mantlui, even with `-e enable_ui=true`

**Comment by siddharthist** [comment]
Works on a fresh cluster, I think something was wrong on the one I tested this on initially.

**Comment by siddharthist** [comment]
On a fresh cluster, the icon shows up in Mantlui, but I get a 404 when navigating to the Web UI.

**Comment by ryane** [comment]
Did you update your local mantl.yml (assuming you're using one) with the changes to sample.yml? I hit the same problem until I remembered to do that... After fixing that, UI came up fine for me

**Comment by siddharthist** [comment]
I think there's an issue with my terraform setup. I'll try again soon. 
```
[centos@ip-10-1-1-11 ~]$ kubectl get nodes 
[centos@ip-10-1-1-11 ~]$
```

**Pull request merged**
