### PR TITLE
updating tooling screenshot

### PR DESCRIPTION
**Pull request by johnswil**
- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

Cisco-cloud-screen-shots/Screen Shot 2016-06-16 at 4.10.46 PM.png

### CODE REVIEW

**Comment by johnswil** [comment]
The path may be wrong, please advise

**Comment by siddharthist** [comment]
@johnswil Could you instead make a PR to replace screenshot.png in [this repo](https://github.com/CiscoCloud/nginx-mantlui)? That way we can update the documentation for both at once :smile: 

Thank you!

**Comment by johnswil** [comment]
I’d like to, however I’m unable to access this branch of the master.  Can’t write any changes on https://github.com/CiscoCloud/nginx-mantlui
I’m perplexed as to how to overwrite.  Do I need more authority?

**Comment by siddharthist** [comment]
@johnswil Here are some docs on contributing changes to repos that you don't have write access to: https://guides.github.com/activities/forking/

**Pull request closed without merging**
