### PR TITLE
failed to unlock neutron ports to allow calico traffic in Openstack b…

### PR DESCRIPTION
**Pull request by yangzhares**
when deploy calico component of Mantl in Openstack, task **unlock neutron ports to allow calico traffic** failed to run because neutron_port_update.py can't parse auth url like **OS_AUTH_URL=https://hf1-keystone-srv.qa.webex.com:443/v2.0**, error log as:

```
*TASK: [calico | unlock neutron ports to allow calico traffic] *****************
failed: [mi-worker-001] => (item=mi-edge-01) => {"changed": false, "cmd": "/usr/local/bin/neutron_port_update.py \"192.168.0.0/16\" \"fa:16:3e:ac:60:18\"", "delta": "0:00:00.514603", "end": "2016-02-25 01:48:08.055803", "failed": true, "failed_when_result": true, "item": "mi-edge-01", "rc": 1, "start": "2016-02-25 01:48:07.541200", "stdout_lines": [], "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/local/bin/neutron_port_update.py", line 128, in <module>
    ports = list_ports(token, public_url)
  File "/usr/local/bin/neutron_port_update.py", line 83, in list_ports
    r = requests.get(auth_url, headers=headers)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 450, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 381, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 357, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: hf1-neutron.qa.webex.com:443v2.0*
```

add slash '/' before 'v2.0/ports' to fix this issue.

### CODE REVIEW

**Comment by loshkovskyi** [comment]
It's the issue #968. The `OS_AUTH_URL` may contain trailing slash or not. That's why it's better use something like this:
```
auth_url = creds['auth_url'].strip('/') + "/tokens"
```

**Comment by yangzhares** [comment]
@loshkovskyi, it seems use like `auth_url = creds['auth_url'].strip('/') + "/tokens"` is a better way. have update it in [f73f1b9](https://github.com/CiscoCloud/mantl/commit/f73f1b95acfda08950479a391cd70e7a3067ee39) and test pass

**Comment by siddharthist** [comment]
@sehqlr Could you test this? I don't have a set up for Openstack, but this looks fine to me.

**Comment by siddharthist** [comment]
we've had successful tests from users and this is pretty simple. merging!

**Pull request merged**
