### PR TITLE
Lock down vault configuration file

### LINKED ISSUE #1493: Vault configuration file should only be readable by root
/etc/vault/vault.hcl is currently readable by any user, but contains our secret `consul_acl_master token`. This file should have mode `0600`. 

- Ansible version (`ansible --version`): n/a
- Python version (`python --version`): n/a
- Git commit hash or branch: master
- Cloud Environment: aws
- Terraform version (`terraform version`): n/a

### PR DESCRIPTION
**Pull request by siddharthist**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

Fixes #1493

### CODE REVIEW

**Comment by siddharthist** [comment]
The CI build is failing unrelatedly, this will need manual testing.

**Comment by siddharthist** [comment]
This works for me on digitalocean:
```
$ ansible role=control --become -a 'ls -alh /etc/vault/vault.hcl'
lb-mi-control-01 | success | rc=0 >>
-rw------- 1 root root 334 Jun  1 17:32 /etc/vault/vault.hcl

lb-mi-control-02 | success | rc=0 >>
-rw------- 1 root root 334 Jun  1 17:32 /etc/vault/vault.hcl

lb-mi-control-03 | success | rc=0 >>
-rw------- 1 root root 334 Jun  1 17:32 /etc/vault/vault.hcl
```
deployed, and everything's healthy!

**Comment by siddharthist** [comment]
rebased for automated testing on other clouds

**Comment by ChrisAubuchon** [comment]
👍

**Pull request merged**
