### PR TITLE
removed not implemented features from calico role

### PR DESCRIPTION
**Pull request by jkramarz**
- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by jkramarz** [comment]
@Zogg, you're working near this code in #1133 . Can I kindly ask you for review?
The API proxy is completely missing, so there's no way to get it working. I'd really like to have it merged, so nobody will get misleaded by documentation of something that does not yet exists in Mantl.

**Comment by jkramarz** [comment]
OK, with help from @loshkovskyi I've tracked the cause.
In 965c91f8 merged in #794, calico image has been changed from the custom one, so it no longer supports these features.
According to https://github.com/mesosphere/marathon/blob/v0.14.0/docs/docs/ip-per-task.md there'll be no way of introducing them again.

**Comment by siddharthist** [comment]
@Zogg Could you take a look at this PR? We might not need it since we're improving/changing Calico integration soon.

**Comment by siddharthist** [comment]
@Zogg Could you review this?

**Comment by siddharthist** [comment]
@Zogg Ping

**Comment by siddharthist** [comment]
Closing this because it's out of date. Please reopen if this is mergeable again!

**Pull request closed without merging**
