### PR TITLE
AWS autoscaling group

### PR DESCRIPTION
**Pull request by joe1chen**
- [x] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

This pull provides a workaround for bug #1339, adding an alternate option to set up an AWS cluster using autoscaling groups.  Note that for now the existing AWS terraform scripts have NOT been changed in any way. Instead I've added new AWS autoscaling scripts so that the end use can choose which implementation to go with.

Differences between regular AWS scripts and autoscaling AWS scripts:
1. Scripts were modified to no longer create individual nodes.
2. 3 launch configurations were created for 1) control nodes, 2) edge nodes, 3) worker nodes.
3. 3 auto-scaling groups were created for 1) control nodes, 2) edge nodes, 3) worker nodes.
4. Elastic load balancers are not created with any nodes initially.  Auto-scaling groups are configured to add new nodes to the ELBs.
5. DNS scripts that create individual A records for the individual nodes will no longer work.

 Currently, without auto-scaling groups, you will not be able to resize your Mantl cluster once you have it up and running due to a Terraform bug.  If you change the cluster size and re-run ``terraform apply``,  Terraform will destroy the EBS data volumes attached to your nodes, re-recreate them, and then  re-attach new volumes to your existing nodes. 

(See https://github.com/hashicorp/terraform/issues/5240 and https://github.com/hashicorp/terraform/issues/5691)

Quick Setup Installations:

1) Use the alternate terraform script:
```
cd mantl
cp terraform/aws-autoscaling.sample.tf ./aws.tf
terraform get
terraform apply
```

2) Setup ansible to use EC2 dynamic inventory file instead of Terraform inventory:
```
pip install -r requirements.txt
export ANSIBLE_HOSTS=plugins/inventory-aws/ec2.py
export AWS_ACCESS_KEY_ID='AK123'
export AWS_SECRET_ACCESS_KEY='abc123'
export AWS_DEFAULT_REGION=us-west-2
```

If you just want to test dynamic inventory file and make sure it's working:
```
./plugins/inventory-aws/ec2.py --list 
```

3) Now wait for a couple minutes until all your EC2 instances have come online.  Make sure they are all pingable:

```
ssh-add ~/.ssh/id_rsa
ansible all -m ping
```

4) Now everything else is the same as a normal mantl setup:
```
ansible-playbook playbooks/upgrade-packages.yml
cp sample.yml mantl.yml
./security-setup
ansible-playbook -e @security.yml mantl.yml
```

### CODE REVIEW

**Comment by crumley** [comment]
ASG also have the benefit of replacing failed nodes automatically. Of course ansible needs to provision them but this is a start. IMO terraform + aws + count is trouble.

**Comment by siddharthist** [comment]
How will nodes that are automatically added by AWS get software (Mesos, K8s, etc.) installed on them?

**Comment by andreimc** [comment]
@siddharthist they won't with this PR, one way to achieve this is to have the nodes self-bootstrapping as in run the playbooks locally when the node comes up, there are a few implications in doing that, how do you get the security.yml, can be put on s3 and pulled on each box. 

Would the playbooks work if for example we ran each nodes individually? eg ansible-playbook -i control, -c local -e @security.yml. Will they form a cluster ? this would be kinda cool

**Comment by siddharthist** [comment]
This is a great idea, I'm just not sure this is going to work with Mantl as it's set up right now. We would need self-provisioning nodes/images, which we're pretty far away from. Please reopen when those factors are in place!

**Pull request closed without merging**
