### PR TITLE
Upgrade Mesos to 0.28.2 and Marathon to 1.1.1

### PR DESCRIPTION
**Pull request by Zogg**
Just be sure to have packages in the repo before merging.

### CODE REVIEW

**Comment by siddharthist** [comment]
LGTM on green

**Comment by siddharthist** [comment]
This is legitimately failing: 
```
TASK: [mesos | install mesos packages] **************************************** 

failed: [mantl-ci-837-3-worker-02] => (item=mesos-0.28.2,cyrus-sasl-md5) => {"changed": false, "failed": true, "item": "mesos-0.28.2,cyrus-sasl-md5", "rc": 0, "results": []}

msg: No Package matching 'mesos-0.28.2' found available, installed or updated

failed: [mantl-ci-837-3-worker-01] => (item=mesos-0.28.2,cyrus-sasl-md5) => {"changed": false, "failed": true, "item": "mesos-0.28.2,cyrus-sasl-md5", "rc": 0, "results": []}

msg: No Package matching 'mesos-0.28.2' found available, installed or updated
```

**Comment by ryane** [comment]
@Zogg does this depend on #1466 being merged first? I see a 0.28.2 version does exist in the `shippedrepos/mantl-1.2` but not in `asteris/mantl-rpm`

**Comment by Zogg** [comment]
@ryane Indeed that is the case.

**Pull request merged**
