### PR TITLE
Move logstash to HOST mode. Update collectd configuration

### PR DESCRIPTION
**Pull request by tymofii-polekhin**
Move Logstash docker container to HOST network mode to use /etc/hosts file for name resolution (kafka-output)
Update collectd configuration

### CODE REVIEW

**Comment by ryane** [comment]
can you provide a little more context around this PR? I am curious why we don't have issues without using `net=host` on other clusters and why we are changing the collectd config?

**Comment by tymofii-polekhin** [comment]
@ryane collectd updated to report absolute values for memory as well as percentages. Also we moving to single overall CPU utilization metric from per-core cause we aggregate then anyway later.
Regarding docker net=host
When Kafka cluster is located in different cluster broker hostnames should be resolvable from container in order to logstash output Kafka to write. When we use net=host docker container does not use host /etc/hosts file for hostnames resolution.

**Comment by siddharthist** [comment]
@tymofii-polekhin Could you explain a bit more about the Kafka issue?

**Comment by siddharthist** [comment]
Closing because this is out of sync and will be further out of sync after we move collectd to an addon and remove it from logstash.

**Pull request closed without merging**
