### PR TITLE
Remove duplicate run_once parameters

### PR DESCRIPTION
**Pull request by tphummel**
I saw these duplicate parameters via `ansible-playbook` warning messages

- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by siddharthist** [comment]
@tphummel Can you explain more about how these are duplicated? I don't see two of them per task or anything... Maybe post the warning that Ansible gave you?

**Comment by tphummel** [comment]
sorry @siddharthist. i could have done a better job adding context. 

so in each of the tasks i've edited, i see two `run_once` parameters. you can see in the diff if you expand the context below the edit. one set to `yes` and the other set to `true`. i should have pasted the warning and now i don't have it in front of me. but it is something along the lines of `warning: parameter declared twice. the last value will be used`. i'm testing out mantl with ansible 2.x, which might be why you don't see the warning. 1.9.x just swallows the warning but i'm pretty sure the behavior (last value wins) is the same. 

this change shouldn't impact the behavior of the roles. i just saw it and thought i would throw a PR together to point it out.

**Comment by tphummel** [comment]
@siddharthist: i found the warnings:
```
 [WARNING]: While constructing a mapping from /Users/tom/Code/connecthq/mantl-
ds/roles/mesos/tasks/leader.yml, line 67, column 3, found a duplicate dict key (run_once).  Using
last defined value only.

 [WARNING]: While constructing a mapping from /Users/tom/Code/connecthq/mantl-
ds/roles/marathon/tasks/conf.yml, line 15, column 3, found a duplicate dict key (run_once).  Using
last defined value only.
```

**Comment by ryane** [comment]
yeah, you can see the duplicates on master:

https://github.com/CiscoCloud/mantl/blob/master/roles/marathon/tasks/conf.yml#L22
https://github.com/CiscoCloud/mantl/blob/master/roles/mesos/tasks/leader.yml#L74

this lgtm

**Pull request merged**
