### PR TITLE
Mantl Design Philosophy

### PR DESCRIPTION
**Pull request by johnswil**
Hi, thank you for your contribution to Mantl! Before we can accept any code into
master, we need it to meet the following criteria. If there are any you can't
satisfy yourself, go ahead and open the pull request anyway and we'll help you
test. Feel free to delete this message once you're done. Thanks again!

- [x] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by siddharthist** [comment]
This will need to show up somewhere in a table of contents, as of right now it's not linked to from anywhere else in the documentation.

**Comment by sehqlr** [comment]
@siddharthist: @johnswil was thinking that this could be linked to in the README. What do you think?

**Comment by siddharthist** [comment]
I think it might be better to link to it from the index page of the docs, but that's not a strong opinion.

**Comment by sehqlr** [comment]
@stevendborrelli Do you have an opinion on this?

**Comment by johnswil** [comment]
It belongs in README, I'm thinking below GOALS just before Architecture

**Comment by siddharthist** [comment]
It needs a file extension and a filename without a space or capitalization. Should be `docs/design-philosophy.rst`.

**Pull request closed without merging**
