### PR TITLE
Fix/docker upgrade 1.1

### LINKED ISSUE #1476: docker package conflict when upgrading 1.0.3 cluster to master
- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.6
- Git commit hash or branch: master
- Cloud Environment: n/a
- Terraform version (`terraform version`): v0.6.11

The latest (as of this writing) version of the redhat docker package that will be installed on 1.0.3 is `1.9.1` and includes the `docker-common-1.9.1-40` package. This will conflict with the `docker-engine-1.11.1` package that we install (by default) in 1.1.

```
Transaction check error:
  file /usr/bin/docker from install of docker-engine-1.11.1-1.el7.centos.x86_64 conflicts with file from package docker-common-1.9.1-40.el7.centos.x86_64
```

### PR DESCRIPTION
**Pull request by ryane**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes (n/a)

Fixes #1476

and includes some doc updates

### CODE REVIEW

**Comment by ryane** [comment]
builds failed for various (likely unrelated) reasons.

aws: 

```
TASK: [wait for host boot] **************************************************** 
...
failed: [mantl-ci-793-1-kubeworker-001 -> 127.0.0.1] => {"elapsed": 120, "failed": true}
msg: Timeout when waiting for 54.153.78.211:22`
```

digitalocean:

```
TASK: [ensure that hosts are responding] ************************************** 
fatal: [mantl-ci-793-2-worker-002] => SSH Error: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
    while connecting to 159.203.200.211:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
```

gce:

```
TASK: [kubernetes | run cert generation script] ******************************* 
failed: [mantl-ci-793-3-control-03 -> 127.0.0.1] => {"cmd": "/mantl/.syncdir/make-ca-cert.sh", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory
```

**Comment by sehqlr** [comment]
That thing is GCE is a Travis-only bug that I started noticing recently that needs an issue made for it.

**Comment by siddharthist** [comment]
I'm testing this manually right now.

**Comment by siddharthist** [comment]
```
TASK: [restart services] ****************************************************** 
changed: [lb0-control-01] => (item=nginx-consul)
failed: [lb0-control-01] => (item=collectd) => {"failed": true, "item": "collectd"}
msg: Failed to stop collectd.service: Unit collectd.service not loaded.
Failed to start collectd.service: Unit collectd.service failed to load: No such file or directory.
```

**Comment by siddharthist** [comment]
Works for me!

**Pull request merged**
