### PR TITLE
terraform assets and support for CenturyLinkCloud

### PR DESCRIPTION
**Pull request by ack**

### CODE REVIEW

**Comment by stevendborrelli** [comment]
Thanks! This is really exciting. 

Do you think we can have a quick google hangout next week to discuss the integration? Send me a note at steve@aster.is

- CLC terraform provisioner
- Travis-CI integration

**Comment by siddharthist** [comment]
Could we remove the inventory commit from this PR now that we have https://github.com/CiscoCloud/terraform.py/pull/36?

**Comment by ack** [comment]
yanked the inventory edits as requested, rebased and squashed commits.

**Comment by siddharthist** [comment]
@ack Thanks for the changes! Have you been able to discuss those topics with @steve?

**Comment by ack** [comment]
Yes, I spoke with steve a while ago. The tf configs for clc should be working. One of our customers has already deployed it (with a custom .terraformrc setup) and we should be all set to merge into mantl. 

The following PR against terraform is nearing completion and with any luck, clc will be included in the provider set for the next tf release. 
https://github.com/hashicorp/terraform/pull/4893

@stevendborrelli  and I also discussed the possibility of integrating acceptance testing on our platform. The next step would be to have someone from mantl/ciscocloud set up an account on our [platform](https://control.ctl.io). We'd be able to grant recurring compute credits for automated testing purposes.

**Comment by siddharthist** [comment]
@ack Sorry, I just merged a conflicting PR. Does the same thing as yours on the Traefik config. Can you fix the conflict? Then we'll merge this, and we can get to work on the CI build immediately after.

**Comment by ack** [comment]
yanked the traefik commit

**Comment by siddharthist** [comment]
@ack And I'm sorry I didn't see this sooner, but I just noticed that the documentation is in the wrong format/spot. Could you add it to `docs/getting_started/clc.rst` and add that page to the table of contents in `docs/getting_started/index.rst`? If you're not sure how to do that, we can merge this and then I'll work on it.

**Comment by ack** [comment]
migrated docs and rebased

**Comment by siddharthist** [comment]
@ack Thanks so much for your work on this! It's all looking good to me, I'm excited to get automated testing up and running.

**Pull request merged**
