### PR TITLE
Kubernetes: Use Mantl TLS certificate

### LINKED ISSUE #1608: kubernetes should use the same certs as everything else
No reason not to, and it'll reduce attack surface, complexity, and code.  

Looks like the certs were valid for the following SAN (from `roles/kubernetes/files/make-ca-cert.sh`):
```
dns_domain="${DNS_DOMAIN:="cluster.local"}"
sans="IP:${service_ip},IP:127.0.0.1,DNS:localhost,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.${dns_domain}"
```
That script is called with the following environment:
```yml
  environment:
    MASTERS: "kubernetes.service.consul"
    DNS_DOMAIN: "{{ dns_domain }}"
    SERVICE_CLUSTER_IP_RANGE: "{{ kube_service_addresses }}"
    CERT_DIR: "{{ playbook_dir }}/{{ cert_syncdir.path }}/certs"
```
so the SAN will really include:
```
DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.service,DNS:kubernetes.default.svc.cluster.local,DNS:kubernetes.service.consul,DNS:kubernetes.default.src.{{ cluster_name or dns_domain }}
```
I don't think we need to have our certs valid for all those names though. Can anyone think of a reason to? 

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

### PR DESCRIPTION
**Pull request by siddharthist**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

the cert isn't valid for the same SANs, but it doesn't seem to matter. if anyone knows of a reason why those DNS names should be valid, please let me know!

fixes #1608, obsoletes #1610

### CODE REVIEW

**Comment by siddharthist** [comment]
CI build passed on all clouds, AWS just timed out while running `terraform destroy`.

**Comment by ryane** [comment]
build completed successfully but I am getting a `502 Bad Gateway` when trying to access the kubernetes UI. The nginx-mantlui proxy is not able to connect to the upstream k8s server(s).

```
2016/07/07 22:54:55 [error] 28#0: *154 connect() failed (111: Connection refused) while connecting to upstream
```

I am not seeing this problem on 1.2.

**Comment by siddharthist** [comment]
@ryane Huh, I didn't see that in my build. Thanks for testing, I'll check on this next week.

**Comment by siddharthist** [comment]
@ryane I'm seeing the same thing now, but I'm not sure how to debug. Everything looks healthy, except the UI won't respond. 
```
[root@lb-control-01 ~]# curl -L -u admin:admin localhost:8085/ui/                           
Error: 'dial tcp 172.17.0.3:9090: connection refused'
Trying to reach: 'http://172.17.0.3:9090/'
```
```
[root@lb-control-01 ~]# kubectl get pods
NAME                                    READY     STATUS    RESTARTS   AGE
kube-apiserver-lb-control-01            1/1       Running   0          1h
kube-apiserver-lb-control-02            1/1       Running   0          1h
kube-apiserver-lb-control-03            1/1       Running   0          1h
kube-controller-manager-lb-control-03   1/1       Running   0          1h
kube-dns-v8-spgpi                       2/2       Running   0          1h
kube-podmaster-lb-control-01            2/2       Running   0          1h
kube-podmaster-lb-control-02            2/2       Running   0          1h
kube-podmaster-lb-control-03            2/2       Running   0          1h
kube-proxy-lb-control-01                1/1       Running   0          1h
kube-proxy-lb-control-02                1/1       Running   0          1h
kube-proxy-lb-control-03                1/1       Running   0          1h
kube-scheduler-lb-control-03            1/1       Running   0          1h
kubernetes-dashboard-5h28t              1/1       Running   0          1h
```
```
[root@lb-control-01 ~]# kubectl logs kubernetes-dashboard-5h28t
2016/07/12 10:42:17 Starting HTTP server on port 9090
2016/07/12 10:42:17 Creating API server client for https://10.254.0.1:443
2016/07/12 10:42:17 Creating in-cluster Heapster client
```
```
[root@lb-control-01 ~]# kubectl get replicationcontrollers
NAME                   DESIRED   CURRENT   AGE
kube-dns-v8            1         1         1h
kubernetes-dashboard   1         1         1h
```

**Comment by siddharthist** [comment]
Closing until this is ready to merge. Please don't delete this branch.

**Comment by siddharthist** [comment]
Looks like our certs need to be valid for more names or something

screenshot

**Pull request closed without merging**
