### PR TITLE
mention bot config

### LINKED ISSUE #1695: Use mention-bot to assign reviewers to PRs
Facebook's mention-bot can analyze git blame history and ask people to review PRs. With proper configuration, it can assign PRs as well:
```
  "assignToReviewer": false, // mention-bot assigns the most appropriate reviewer for PR
```
https://github.com/facebook/mention-bot

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

### PR DESCRIPTION
**Pull request by siddharthist**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

I already enabled the webhook so this PR is also a test :)

config options available here: https://github.com/facebook/mention-bot

fixes #1695

manually skipped ci build

### CODE REVIEW

**Comment by siddharthist** [comment]
It works! See #1704.

**Comment by ryane** [comment]
would it be possible to use a whitelist of reviewers to mention?

**Comment by siddharthist** [comment]
@ryane The configuration shown here will only ping users from CiscoCloud or asteris-llc. I don't think we can whitelist a specific set of users other than by organization. We could make a new GH org though! 

We can blacklist users, though.

**Comment by ryane** [comment]
the org list is probably fine but it looks it might not be working. see #1708

**Comment by siddharthist** [comment]
@ryane That's because this PR hasn't been merged :wink: we're using the default config rn

**Comment by ryane** [comment]
hah, ok.  well lgtm then

**Pull request merged**
