### PR TITLE
add readme and defaults for end-to-end ssl over traefik

### PR DESCRIPTION
**Pull request by kbroughton**
Work in progress to share with others.  Not ready.

- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by distributorofpain** [comment]
still trying to understand how this works....   and how traefik works with marathon in general as well.  I would like to set this up, but i cant seem to get my containers to show up properly to traefik, so i wonder if the script is even running.  The backend still shows as severname:port which is still invalid cert wise.  I am assuming the script registers with consul and presents the app as appname.service.consul?  which traefik then pulls in?

**Comment by kbroughton** [comment]
The script isn't fully baked yet.  I'm working on it again now.  I pushed it early just so people could have an outline of how to do it. 

I'll push with much better automation by end of tomorrow hopefully.  Right now i'm struggling with the fact that the latest pull of mantl master no longer has marathon registering names as mantl-worker-001.node.consul.  Rather they show up as just mantl-worker-001.  WIthout a domain, there is no way I can get a self signed CA wildcard cert.  Once this is solved i can push.

**Comment by distributorofpain** [comment]
thanks for confirming the issue!  I might just have to rebuild on an older pull so i can get this working.  It just complicates things...  hopefully i can keep the cert and reuse it since its generated on the orchestration server.

**Comment by kbroughton** [comment]
This is now working building off the feature/certificates-role branch.
The wildcard_ssl.yml could be moved to common and ssl folder could have slots like ssl/external_certs and ssl/external_keys with a few variables like traefik_routed_cert_path, traefik_routed_key_path to indicate where traefik should load material for external facing ssl termination.  I would suggest it be included in roles/common/tasks/main.yml with 
```
- include: external_ssl.yml
  when: "do_external_ssl == 'true'"
```

also note there was an issue with prior pushes setting /private_certs to 0400 permission which made the directory un-readable.

**Comment by distributorofpain** [comment]
With the changes in the feature/certificates-role branch, how am i supposed to put an SSL cert into the docker image, is that something that should be loaded on app start up ( being that apps start on different worker nodes ).

**Comment by siddharthist** [comment]
@distributorofpain You can mount Mantl's TLS certificates in your container using a volume. There's an example of this [in the Marathon docs](https://mesosphere.github.io/marathon/docs/native-docker.html).

**Comment by distributorofpain** [comment]
well, i was able to get the application to pull in the certificate from the host as suggested ( @siddharthist  ), but now traefik doesnt like the certificate authority...  argh! :frowning: 

```
Jun  7 00:58:13 mantl-do-nyc2-edge-01 traefik: time="2016-06-07T00:58:13Z" level=error msg="Error forwarding to https://mantl-do-nyc2-worker-001:7254, err: x509: certificate signed by unknown authority"
```

Being that all the servers were built using the same setup and that the certs generate on each host, how can you get traefik to trust each host server as the authority?

**Comment by siddharthist** [comment]
@kbroughton I'll be able to review this once #1463 is merged.

**Comment by siddharthist** [comment]
@kbroughton Also: does this superscede #1378?

**Comment by kbroughton** [comment]
I would say so.  Though you might include something like 1378 as a pin-point fix, it uses self-signed certs which causes problems for presenting to customers and for sometimes for 3rd party monitoring/alerting.

1378 uses the same self-signed cert for hosts and traefik.  My PR uses self-signed on the backend and assumes a proper cert for traefik routes.  Mine should definitely default to using the self-signed host certs if proper certs are not available, but it doesn't to this yet.

**Comment by siddharthist** [comment]
@kbroughton Can you update this to work with the new certificate setup?

**Comment by kbroughton** [comment]
I think having --dns and --ip variables in certificates/defaults/main.yml
will provide the flexibility i need and make this pr obsolete.

However, my setup generates DNS:10.201.4.238, DNS:10.201.4.238.node,
DNS:10.201.4.238.node.consul by default.
inventory_hostname varies a lot depending on cloud-provider and
customizations to dynamic inventory script.  So ansible_fqdn or something
like that might be better.

Certificates Rotation:
On trying to add a flag to certificates/tasks/main.yml to remove the
/etc/pki/mantl/cert file (checked by "creates") I see this error.
Looks like it's related to
https://rt.openssl.org/Ticket/Display.html?id=502&user=guest&pass=guest
Any ideas on how to properly rotate with this technique?

failed: [d-lin-auw2-worker02] => {"changed": true, "cmd":
["generate-certificate", "--dns", "d-lin-auw2-worker02
d-lin-auw2-worker02.node d-lin-auw2-worker02.node.consul *.service
*.service.consul", "--ip", "10.201.2.26", "--location",
"d-lin-auw2-worker02", "--destination", "/etc/pki/mantl"], "delta":
"0:00:00.319508", "end": "2016-07-11 19:59:20.490939", "rc": 1, "start":
"2016-07-11 19:59:20.171431", "warnings": []}
stderr: Generating RSA private key, 2048 bit long modulus
....................................+++
.........................................................................................................................................................+++
e is 65537 (0x10001)
Using configuration from openssl-req.cnf
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number: 1048579 (0x100003)
        Validity
            Not Before: Jul 11 19:59:20 2016 GMT
            Not After : Jul 11 19:59:20 2017 GMT
        Subject:
            countryName               = US
            stateOrProvinceName       = New York
            organizationName          = Example Company Inc
            organizationalUnitName    = Operations
            commonName                = d-lin-auw2-worker02
            emailAddress              = operations@example.com
        X509v3 extensions:
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Digital Signature, Key Encipherment
            Netscape Comment:
                OpenSSL Generated Certificate
            X509v3 Subject Key Identifier:
                99:95:DB:38:90:8C:5A:AB:18:4F:66:59:37:61:32:DA:CF:E8:6E:62
            X509v3 Authority Key Identifier:

keyid:DC:5C:13:2A:2A:04:AA:50:36:28:16:D1:25:4A:7E:59:D0:3C:A4:13

            X509v3 Subject Alternative Name:
                DNS:localhost, DNS:d-lin-auw2-worker02,
DNS:d-lin-auw2-worker02.node, DNS:d-lin-auw2-worker02.node.consul,
DNS:*.service, DNS:*.service.consul, IP Address:127.0.0.1, IP
Address:10.201.2.26
Certificate is to be certified until Jul 11 19:59:20 2017 GMT (365 days)
failed to update database
TXT_DB error number 2
stdout: Error generating cert

On Mon, Jul 11, 2016 at 4:55 AM, Langston Barrett <notifications@github.com>
wrote:

> @kbroughton <https://github.com/kbroughton> Can you update this to work
> with the new certificate setup?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CiscoCloud/mantl/pull/1445#issuecomment-231691275>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKErsuFn6J9OptMnjtIMSgGYyA-bg9VXks5qUhMvgaJpZM4Idp7F>
> .
>



-- 
kesten broughton
devops @ cognitivescale

**Comment by kbroughton** [comment]
Adding this above "generate certificates" task fixes it for me.  Of course
cert revocation of previous would be better.

- name: set unique_subject = no
  copy:
    dest: "/etc/pki/CA/index.txt.attr"
    content: "unique_subject = no"
    mode: 0644
  tags:
    - certificates

On Mon, Jul 11, 2016 at 3:24 PM, Kesten Broughton <
kbroughton@cognitivescale.com> wrote:

> I think having --dns and --ip variables in certificates/defaults/main.yml
> will provide the flexibility i need and make this pr obsolete.
>
> However, my setup generates DNS:10.201.4.238, DNS:10.201.4.238.node,
> DNS:10.201.4.238.node.consul by default.
> inventory_hostname varies a lot depending on cloud-provider and
> customizations to dynamic inventory script.  So ansible_fqdn or something
> like that might be better.
>
> Certificates Rotation:
> On trying to add a flag to certificates/tasks/main.yml to remove the
> /etc/pki/mantl/cert file (checked by "creates") I see this error.
> Looks like it's related to
> https://rt.openssl.org/Ticket/Display.html?id=502&user=guest&pass=guest
> Any ideas on how to properly rotate with this technique?
>
> failed: [d-lin-auw2-worker02] => {"changed": true, "cmd":
> ["generate-certificate", "--dns", "d-lin-auw2-worker02
> d-lin-auw2-worker02.node d-lin-auw2-worker02.node.consul *.service
> *.service.consul", "--ip", "10.201.2.26", "--location",
> "d-lin-auw2-worker02", "--destination", "/etc/pki/mantl"], "delta":
> "0:00:00.319508", "end": "2016-07-11 19:59:20.490939", "rc": 1, "start":
> "2016-07-11 19:59:20.171431", "warnings": []}
> stderr: Generating RSA private key, 2048 bit long modulus
> ....................................+++
>
> .........................................................................................................................................................+++
> e is 65537 (0x10001)
> Using configuration from openssl-req.cnf
> Check that the request matches the signature
> Signature ok
> Certificate Details:
>         Serial Number: 1048579 (0x100003)
>         Validity
>             Not Before: Jul 11 19:59:20 2016 GMT
>             Not After : Jul 11 19:59:20 2017 GMT
>         Subject:
>             countryName               = US
>             stateOrProvinceName       = New York
>             organizationName          = Example Company Inc
>             organizationalUnitName    = Operations
>             commonName                = d-lin-auw2-worker02
>             emailAddress              = operations@example.com
>         X509v3 extensions:
>             X509v3 Extended Key Usage:
>                 TLS Web Server Authentication, TLS Web Client
> Authentication
>             X509v3 Basic Constraints:
>                 CA:FALSE
>             X509v3 Key Usage:
>                 Digital Signature, Key Encipherment
>             Netscape Comment:
>                 OpenSSL Generated Certificate
>             X509v3 Subject Key Identifier:
>                 99:95:DB:38:90:8C:5A:AB:18:4F:66:59:37:61:32:DA:CF:E8:6E:62
>             X509v3 Authority Key Identifier:
>
> keyid:DC:5C:13:2A:2A:04:AA:50:36:28:16:D1:25:4A:7E:59:D0:3C:A4:13
>
>             X509v3 Subject Alternative Name:
>                 DNS:localhost, DNS:d-lin-auw2-worker02,
> DNS:d-lin-auw2-worker02.node, DNS:d-lin-auw2-worker02.node.consul,
> DNS:*.service, DNS:*.service.consul, IP Address:127.0.0.1, IP
> Address:10.201.2.26
> Certificate is to be certified until Jul 11 19:59:20 2017 GMT (365 days)
> failed to update database
> TXT_DB error number 2
> stdout: Error generating cert
>
> On Mon, Jul 11, 2016 at 4:55 AM, Langston Barrett <
> notifications@github.com> wrote:
>
>> @kbroughton <https://github.com/kbroughton> Can you update this to work
>> with the new certificate setup?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/CiscoCloud/mantl/pull/1445#issuecomment-231691275>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AKErsuFn6J9OptMnjtIMSgGYyA-bg9VXks5qUhMvgaJpZM4Idp7F>
>> .
>>
>
>
>
> --
> kesten broughton
> devops @ cognitivescale
>



-- 
kesten broughton
devops @ cognitivescale

**Comment by siddharthist** [comment]
@kbroughton If you're looking to rotate your certs, check out #1605. 

We'd still love to see some documentation on setting up end-to-end ssl if you'd like to make a new PR!

**Pull request closed without merging**
