### PR TITLE
adding terraform/openstack group creation(Issue #625) and auth/vars r…

### PR DESCRIPTION
**Pull request by antimack**
Adding terraform/openstack group creation(Issue #625) and auth/vars refactoring with adding terraform.tfvars .

### CODE REVIEW

**Comment by loshkovskyi** [comment]
What do core comitters think about this pull request? Should the security group be implemented with tfvars or without them using current Terraform configuration?

**Comment by loshkovskyi** [comment]
@matjohn2, @PeterLamar what do you think about this PR?

**Comment by siddharthist** [comment]
Since the merge of #901, this is out of date. What should be done @stevendborrelli? Is this issue still relevant?

**Comment by loshkovskyi** [comment]
Yes, it's definitely out of date after being ignored for almost 2 months.

**Pull request closed without merging**
