### PR TITLE
Provider is defined condition added

### LINKED ISSUE #1062: Provider undefined in marathon task
This line does not check to see if `provider` is defined and creates an error during bare metal installs:

https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/marathon/tasks/jobs.yml#L3

Replace with:

```
 when: provider is defined and provider == "vagrant"
```

### PR DESCRIPTION
**Pull request by TanyaCouture**
Fixes #1062

### CODE REVIEW

**Comment by siddharthist** [comment]
LGTM!

**Comment by sehqlr** [comment]
What do we need to do to test this? In the issue, Steve said that it was interfering with bare metal installs, so I don't know how to test.

**Comment by siddharthist** [comment]
@sehqlr I would say try an install on Vagrant. Shouldn't be too complex.

**Comment by siddharthist** [comment]
Rebasing to trigger CI build.

**Comment by ryane** [comment]
while this doesn't break anything, I noticed that it doesn't actually have any effect when doing a regular vagrant install:

```
TASK: [marathon | ensure job docker images are present] ***********************
skipping: [control-01] => (item=ciscocloud/mesos-consul:v0.3.2)
skipping: [control-01] => (item=ciscocloud/mantl-api:0.1.5)
```

It does look like that task will run when building the vagrant image via packer though. To make it work on regular vagrant builds, I think we would need to make this change:

```diff
diff --git a/Vagrantfile b/Vagrantfile
index 1da4153..fabb707 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -148,7 +148,7 @@ Vagrant.configure(2) do |config|
             "ansible_ssh_user" => "vagrant",
             "ansible_ssh_pass" => "vagrant",
             "consul_dc" => "vagrantdc",
-            "provider" => "virtualbox",
+            "provider" => "vagrant",
             "publicly_routable" => true
           }
         }
```

I'm not sure why provider is set to virtualbox here. Is this a mistake?

In any case, I am thinking we should remove this task entirely and let marathon handle the docker pull. It doesn't even make sense on vagrant anymore since this task only runs on control nodes and these containers run on worker nodes (and vagrant provisions a worker node by default now).

ping @siddharthist @stevendborrelli

**Comment by siddharthist** [comment]
cc #1184

**Comment by ryane** [comment]
replaced by #1218

**Pull request closed without merging**
