### PR TITLE
Move travis build steps into a "switchboard" run-tests script

### PR DESCRIPTION
**Pull request by sehqlr**
Our CI setup was complex to start with, and the complexity is
increasing. To help with this, I moved much of the setup logic from the
travis config file to a separate script. This will allow us to skip
certain builds (such as documentation) and it will handle more complex
cases, such as accessing a jump box, only trigger cloud deploys in
certain situations, and so on.

This is mostly a refactoring, with little logic changes.

### CODE REVIEW

**Comment by siddharthist** [comment]
Could we also skip the build when no secrets are defined?

**Comment by sehqlr** [comment]
I was planning on working on that after the initial port and ssh'ing into a jump box

**Comment by sehqlr** [comment]
I want to merge #1261 before this. When that happens, it's likely there will be merge conflicts.

**Comment by sehqlr** [comment]
#1289 supersedes this

**Pull request closed without merging**
