### PR TITLE
Add iptables role

### PR DESCRIPTION
**Pull request by eirslett**
This role lets you restrict incoming IP traffic for the
cluster to only internal cluster members. A README file
describes more in detail how it works.

### CODE REVIEW

**Comment by rarruda** [comment]
+1

**Comment by siddharthist** [comment]
@eirslett Is this ready for testing?

**Comment by eirslett** [comment]
Yes, it is. This is what we're running on our test data center now.
I'm not quite sure why the build failed... Haven't tried it on OpenStack yet. Does it work if it's run manually?

**Comment by siddharthist** [comment]
@eirslett That build is unreliable to say the least. Many of the PRs we merge start with failing builds. We're working on improving our automated testing. I will test this soon.

**Comment by siddharthist** [comment]
@eirslett Initial testing on Openstack looks good :smile:

**Comment by eirslett** [comment]
That's good to hear!
I had some thoughts about security:

1) Since the consul ports are open to the world, it can be DDoS-ed. One way to avoid that could be to make consul only listen to private IPs, which would reduce the range of incoming IP addresses to only ones on the same private network (some providers, like DigitalOcean, do shared private networking, which means other DO customers could potentially launch a DDoS from their droplets, but that's probably not a realistic option)

2) With this setup, any IP address can join the cluster, so if somebody obtains the Consul access credentials, they have internal network access to the whole data center. Hopefully, the rate limiting should restrict any brute-forcing efforts from a single IP, but a botnet might be able to brute-force the credentials for consul if they're not strong enough. (I'm not sure whether the consul cluster would fail to handle the load, or if it would be brute-forced eventually)
The second issue would also be mitigated by letting consul use private IPs exclusively - in the OD case, launching an attack via droplets in the same data center would probably be hindered by the rate-limiting.

3) If consul is attacked, and eventually crashes due to high load, that has a serious impact on the whole infrastructure. One option is to only open consul ports on a minority of control nodes (and no worker nodes), so even if it crashes, only a minority of the consul server nodes will be down and the cluster as a whole will still function.

**Comment by siddharthist** [comment]
@eirslett Just a note: if/when this is merged, it needs automated tests. A ticket should be opened in [distributive-rpm](https://github.com/CiscoCloud/distributive-rpm), and it would be great if you'd be willing to help out with that. If not, I can cover it.

**Comment by eirslett** [comment]
I can have a look; what kind of tests do you think would be appropriate for this role?

**Comment by siddharthist** [comment]
@eirslett We can cross that bridge when we come to it, but we generally try for at least a test to verify each Ansible task.

**Comment by eirslett** [comment]
Tests were added here: https://github.com/CiscoCloud/distributive-rpm/pull/11
I'm not sure how to test them against MI; I just copied code from the other tests.

**Comment by siddharthist** [comment]
@eirslett Really sorry for the long delay on this one, we've had a few conversations about it internally and wanted to see what you thought about packaging this as an addon, like Gluster. Does that sound appropriate?

**Comment by eirslett** [comment]
Sure, sounds like a good idea.

**Comment by siddharthist** [comment]
It looks like we'd just have to make an iptables playbook under addons/, and take the one line out of terraform.sample.yml. Would you like to do that? Or, I can also put in a PR to this branch.

**Comment by gregdurham** [comment]
Just a thought, but what about using [ferm](http://ferm.foo-projects.org/) and add iptables rules on a role by role basis, and using a handler to compile all of them together?

**Comment by siddharthist** [comment]
I have created PR to @eirslett's branch here: https://github.com/eirslett/microservices-infrastructure/pull/1. Once that is merged, this will be packaged as an addon, and we can proceed with testing and merging.

**Comment by siddharthist** [comment]
@eirslett Hate to do this do you when you've been so patient here, but would you mind rebasing this onto current master? My terraform configurations don't work with this as-is, so I can't test it yet.

**Comment by eirslett** [comment]
I rebased it on top of master now!

**Comment by siddharthist** [comment]
@eirslett I'm having some unrelated trouble on our Openstack test setup. I'll try to fix it and test in the morning!

**Comment by siddharthist** [comment]
I get the following error on DigitialOcean:
```
TASK: [iptables | deploy iptables configuration] ****************************** 
changed: [lb-mi-control-02] => (item={'dest': '/etc/consul-template/config.d', 'src': 'iptables-core.cfg'})
changed: [lb-mi-control-01] => (item={'dest': '/etc/consul-template/config.d', 'src': 'iptables-core.cfg'})
changed: [lb-mi-control-03] => (item={'dest': '/etc/consul-template/config.d', 'src': 'iptables-core.cfg'})
ERROR: change handler (reload consul-template) is not defined
```

**Comment by siddharthist** [comment]
I see the error, I'll make a PR with the fix.

**Pull request merged**
