### PR TITLE
Add GlusterFS to k8s

### PR DESCRIPTION
**Pull request by andreimc**
Added k8s to the gluster role.

Tested and forms the same k8s cluster visible to all workers.

- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by siddharthist** [comment]
@sehqlr: could the new folks help with testing this?

**Comment by siddharthist** [comment]
@andreimc Sorry for the delay, we're still working on testing this. I believe @sehqlr will be helping @nigerianlegend with that today, so I'm going to assign this PR to them.

**Comment by andreimc** [comment]
Cool I tested this on AWS

**Comment by siddharthist** [comment]
Works for me:
```
[centos@mantl-kubeworker-002 ~]$ sudo touch /mnt/container-volumes/TEST2
[centos@mantl-kubeworker-002 ~]$ exit
logout
Connection to 52.37.228.122 closed.
code/mantl2 > mantl_ssh control
Warning: Permanently added '52.42.212.61' (ECDSA) to the list of known hosts.
Last login: Fri Jul 29 11:25:44 2016 from fs.svanette.ch
[centos@mantl-control-03 ~]$ ls /mnt/container-volumes/
TEST  TEST2
```

**Comment by siddharthist** [comment]
I went ahead and cherry picked your commit to master rather than merging the PR, just to keep our git history a little cleaner. You can see it in master here: https://github.com/CiscoCloud/mantl/commit/fe2d5bb8a81ab473ea93945a16991a45820f5a70

**Comment by andreimc** [comment]
👍

**Pull request closed without merging**
