### PR TITLE
k8s: ability to access k8s api remotely

### LINKED ISSUE #1627: kubernetes api should be available remotely
Users should be able to run kubectl remotely. We need to make the kubernetes api available remotely in a secure fashion.

### PR DESCRIPTION
**Pull request by ryane**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

fixes #1627

depends on https://github.com/CiscoCloud/nginx-mantlui/pull/24

### CODE REVIEW

**Comment by siddharthist** [comment]
Testing now.

**Comment by siddharthist** [comment]
Got
```
failed: [lb-control-03] => {"changed": true, "cmd": ["/usr/bin/docker", "pull", "ciscocloud/nginx-mantlui:0.7.0"], "delta": "0:00:02.158710", "end": "2016-07-11 10:24:36.199939", "rc": 1, "start": "2016-07-11 10:24:34.041229", "warnings": []}
```

I think what happened is that there was no git tag, and so the `deploy` section of `nginx-mantlui` only deployed to the `edge` tag, instead of `0.7.0`.

**Comment by ryane** [comment]
that's right. the build is only set to push a new versioned image when tagged as a release. I just did that and 0.7.0 is now in docker hub. 

sorry about that - I probably should have noted that.

**Comment by siddharthist** [comment]
@ryane No problem, I'm testing again now :)

**Comment by siddharthist** [comment]
This isn't working for me:
```
$ kubectl config set-cluster mantl --insecure-skip-tls-verify=true --server=https://<redacted>/kubeapi
cluster "mantl" set.
$ kubectl config set-credentials mantl-basic-auth --username=admin --password=<redacted>
user "mantl-basic-auth" set.
$ kubectl config set-context mantl --cluster=mantl --user=mantl-basic-auth
context "mantl" set.
$ kubectl config use-context mantl
switched to context "mantl".
$ kubectl get pods
$ 
```

**Comment by ryane** [comment]
do you get results if you run

`kubectl get pods --all-namespaces`

?

**Comment by siddharthist** [comment]
Got it working! Thanks for the help @ryane

**Pull request merged**
