### PR TITLE
Feature/single cert

### PR DESCRIPTION
**Pull request by ChrisAubuchon**
- [X] Installs cleanly on a fresh build of most recent master branch
- [X] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

This PR removes the individual application certificates (`vault.cert, consul.cert, nginx.cert, etc`) and creates a single certificate instead.

### CODE REVIEW

**Comment by ChrisAubuchon** [comment]
The upgrade will require a rerun of `security-setup` to generate the single certificate.

**Comment by ryane** [comment]
on a new build (with an updated security.yml and merged with master), I am seeing nginx-consul fail to start:

```
Apr 29 11:16:21 resching-gce-control-03 docker[10263]: nginx: [emerg] BIO_new_file("/etc/nginx/ssl/nginx.cert") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/nginx.cert','r') error:2006D080:BIO routines:BIO_new_file:no such file)
Apr 29 11:16:21 resching-gce-control-03 docker[10263]: nginx: configuration file /etc/nginx/nginx.conf test failed
Apr 29 11:16:21 resching-gce-control-03 docker[10263]: nginx.conf check failed...
```

**Comment by ryane** [comment]
https://github.com/CiscoCloud/mantl/blob/feature/single-cert/roles/consul/tasks/nginx_proxy.yml#L2

it looks like this is still using files/consul.nginx and not templates/consul.nginx.j2

**Comment by ryane** [comment]
also, looks like we need to update the elb configs to use the new cert path:

* https://github.com/CiscoCloud/mantl/blob/feature/single-cert/terraform/aws/elb/main.tf#L1
* https://github.com/CiscoCloud/mantl/blob/feature/single-cert/terraform/aws/elb/traefik/main.tf#L1

**Comment by ChrisAubuchon** [comment]
```it looks like this is still using files/consul.nginx and not templates/consul.nginx.j2```

It's supposed to use `files/consul.nginx`. `templates/consul.nginx.j2` should be gone. Joys of rebasing I suppose.

**Comment by ryane** [comment]
Get the following failed Consul check on all nodes:

```
common Distributive Mantl Health Checks
...
No such file or directory: /etc/pki/ca-trust/source/anchors/cacert.pem
```

Looks like we either need an updated distributive check or restore the old file name of the root cert.

ping @siddharthist

**Comment by ChrisAubuchon** [comment]
Any other checks failing because of hardcoded file names?

**Comment by ryane** [comment]
if I do 

```
ansible all -s -m shell -a 'cp /etc/pki/ca-trust/source/anchors/ca.cert /etc/pki/catrust/source/anchors/cacert.pem'
```

I go all green

**Comment by ChrisAubuchon** [comment]
Go ahead and change the path. It's not that important. Probably easier and less trouble than modify a distributive check.

**Comment by ryane** [comment]
@ChrisAubuchon I had to make one more fix for mesos and marathon. that last commit look ok to you?

**Comment by ChrisAubuchon** [comment]
Sigh. Rebasing is fun. The last commit looks good.

**Comment by ryane** [comment]
gce build passed. do and aws builds failed for what appear to be unrelated reasons.

manually tested on aws and and upgrade from 1.0.3 on gce. lgtm

**Pull request merged**
