### PR TITLE
Mesos 0.27.1, Kubernetes and Calico: inter-scheduler networking

### PR DESCRIPTION
**Pull request by Zogg**
This is a branch that joins together two branches (mesos and kube) of work done on calico integration. This branch uses mesos 0.26 compiled with netmodules, along with marathon .14, kubernetes 1.1.4 and calico 0.15.0 .

Kubernetes and Mesos tasks will be assigned an unique IP address from calico address pool, thus allowing tasks/containers running on different schedulers to exchange network traffic, as long as both tasks are running in the same Network security group (netgroup). Netgroups only allow network traffic between tasks that have at least one of their configured groups in common. 

Currently, on mesos, only NON-DOCKERIZED marathon tasks support IP assignment (marathon's current limitation): https://github.com/mesosphere/marathon/blob/v0.14.0/docs/docs/ip-per-task.md
@matjohn2 
@stevendborrelli 

Tested on:
* GCE

### CODE REVIEW

**Comment by matjohn2** [comment]
This is wunderbar! Thanks for bringing it all together in one place. Spinning this up now to take a look.

**Comment by anners** [comment]
What is the status of this PR?

**Comment by Zogg** [comment]
@anners About to be merged in.

**Comment by BrianHicks** [comment]
Right, here's the new plan: to the best of my understanding this is blocked by a Calico bug. I'm going to start pulling this apart into little bits that we can merge into mainline so that master's k8s support can improve, even if everything else is still blocked.

**Comment by BrianHicks** [comment]
Given the commit history, it looks like we'll have this smaller PRs (I've tried to order them but it may shake out differently):

1. dedicated kubernetes worker for all clouds
1. clean up "old" Kubernetes roles (commits like ca19c5dcbc841da19dfd1c10925839124df21baf)
1. update Kubernetes version to 1.2 (1.1 in this PR)
1. enable Kubernetes by default, only configured if worker present
1. enable calico by default.

And all on top of latest master.

Open questions:

- @anners, @matjohn2: shall we continue to support Flannel until the Calico bug is fixed, or consider it completely blocking? (@zogg is off today, and we can get more details about it from him tomorrow.) This effects merge order of split PRs.
- @zogg: can you explain all the logging stuff in eafef224d76efa915808c1183eb57407ef0969e4? Why is this included by default? Wouldn't it be better to use the ELK addon, if installed?

**Comment by BrianHicks** [comment]
For later reference, I have currently cherry-picked all commits up to 1ea3ccc into `feature/k8s-by-default`.

**Comment by jkramarz** [comment]
@Zogg, I think it won't be possible to merge this pull request any soon because #863 got already reverted in #995, because of mesos/elasticsearch#457 which is a result of [MESOS-4449](https://issues.apache.org/jira/browse/MESOS-4449). Is it possible to provide custom builds of mesos/elasticsearch docker image?

**Comment by siddharthist** [comment]
@jkramarz If you take a look at the commit history, 0.26 is changed to 0.27. I've updated the issue title accordingly!

**Comment by jkramarz** [comment]
@siddharthist, it's good to hear that!
According to https://github.com/projectcalico/calico-mesos-deployments/blob/master/docs/UsingCalicoMesos.md there will be a way to use it with Docker on Marathon, so I'm super-happy :-)

**Comment by siddharthist** [comment]
@Zogg @BrianHicks Is there a reason to keep this PR open? It seems that the only thing left on your list is integrate Calico, which is blocked.

**Comment by dbathgate** [comment]
@BrianHicks what is the bug in Calico that is blocking this PR?

**Comment by BrianHicks** [comment]
@zogg :arrow_up:

**Comment by Zogg** [comment]
@dbathgate https://issues.apache.org/jira/browse/MESOS-5061

**Comment by siddharthist** [comment]
Now that we've nailed down the Calico bug (can't seem to find where right now), what's the status of this PR?

**Comment by siddharthist** [comment]
Closing in favor of #1521

**Pull request closed without merging**
