### PR TITLE
Examples/spark fix

### PR DESCRIPTION
**Pull request by mcapuccini**
I have now experimented for a while running Spark jobs in MANTL. This fixes the previous example, where for a higher N passed as argument to SparkPi, a network exception occurred. I am not sure why this was happening, but it was probably due to a problem with port mappings in the executor docker containers. In this new example docker is used only to submit the job to the Spark dispatcher, and then the executor are deployed using spark.executor.uri. Furthermore, I figured out a couple of tricks that reduce the number of prerequisites to run the example. The source code of my custom spark-mantl docker image is at: https://github.com/mcapuccini/spark-container

### CODE REVIEW

**Comment by siddharthist** [comment]
@mcapuccini Could we link to your container source in the README?

**Comment by mcapuccini** [comment]
@siddharthist sure, I just linked it

**Comment by siddharthist** [comment]
I got this error:
```
$ ./schedule.sh
Please insert your MANTL control node IP address (or domain name)
xxxxxxxxxx
Please instert your MANTL admin password:
HTTP/1.1 204 No Content
Server: nginx/1.6.2
Date: Tue, 26 Apr 2016 18:28:02 GMT
Content-Type: application/json
Connection: keep-alive
```

**Comment by mcapuccini** [comment]
@siddharthist 204 it means OK, with empty response in the HTTP protocol. It is not an error. Unfortunately Chronos does not return any entity-body with useful messages. 

I'll fix the typo.

**Comment by siddharthist** [comment]
@mcapuccini Thanks!

**Pull request merged**
