### PR TITLE
vSphere Provider Fixes including linked clones, folders, and private_…

### PR DESCRIPTION
**Pull request by hpreston**
In doing testing against vSphere as the provider I hit the following that I've made some simple changes to resolve: 

-  Add support for linked_clone use with the deployed VMs
- Add support for deploying to folders in vCenter 
  - The vsphere terraform provider already supported, just needed to update the vsphere.sample.tf and vsphere/main.tf to support it
  - Set defaults to "false" for linked_clone and no folder 

- The dynamic inventory file for terraform was missing an attr for "private_ipv4" that is needed when running playbook to install Mantl.  Added it to the inventory file.

### CODE REVIEW

**Comment by siddharthist** [comment]
Thank you! Fixes for terraform.py should be made [in this repo](https://github.com/CiscoCloud/terraform.py). What do you think of these changes @chrislovecnm?

**Comment by hpreston** [comment]
I didn't realize there was a different repo for the inventory function.  I just looked and the same change I made is already in that repo, but it hasn't been synced to CiscoCloud/microservices-infrastructure yet.  If you can sync the code over it'll fix that bug.

**Comment by siddharthist** [comment]
Sounds good! Here are the steps that need to be taken before merging this: 
 - [ ] Close #986 
 - [ ] Get a review from someone more knowledgeable about vSphere
 - [ ] Test

**Comment by siddharthist** [comment]
This is out of sync with master and still has a change to `terraform.py`. Would you mind removing that and rebasing, @hpreston?

**Comment by hpreston** [comment]
Yep, I can definitely get it updated.  Thanks!

**Comment by hpreston** [comment]
I'm working on updating this now and testing with the latest terraform and native vsphere provider. There are some conflicts to work through.  I'll update my repo when it's all straightened back out.

**Comment by hpreston** [comment]
@siddharthist Okay, I've completed all the updates to my fork to reflect the latest commits in the master.  There are some bugs in the current master and vSphere deploy with conflicts in attributes between what terraform is generating for the inventory related to ip_addresses for the hosts that I fixed along with adding support for vSphere folders and some additional options for RAM and CPUs in the sample.tf file.  Can we get this merged in before I get too far out of sync again?

**Comment by siddharthist** [comment]
@hpreston Thanks! We just need @chrislovecnm's +1.

**Comment by chrislovecnm** [comment]
:+1:

**Pull request merged**
