### PR TITLE
Kubernetes alongside mesos in one cluster

### PR DESCRIPTION
**Pull request by Zogg**
Dedicated workers for kubernetes kubelets.

From now on, to enable kubernetes one has only to increase a number of 'kube_worker_count' in the .tf file, and kubernetes master/minions will be deployed automatically. Because of that, `terraform.sample.yml` has kubernetes and etcd roles added by default. When 'kube_worker_count' is zero, the k8s roles are skipped.

Kubernetes variables are to be found at group_vars/all/kubernetes_vars.yml

This PR addresses following issues:
* https://github.com/CiscoCloud/microservices-infrastructure/issues/891
* https://github.com/CiscoCloud/microservices-infrastructure/issues/836

## Status 
Tested on:
* GCE: works
* AWS: - works
* OS: -

### CODE REVIEW

**Comment by stevendborrelli** [comment]
Is there a way we can make the host terraform definitions more generic, so that they can be used for different roles?

for example:

```
module "mesos-worker" {
   source = "tf/gce"
   metadata = "role=worker"
}

module "mesos-worker" {
   source = "tf/gce"
   metadata = "role=k8s-worker"
}
``

**Comment by Zogg** [comment]
@stevendborrelli I'll try to get the abstracted modules into dedicated PR/issue.

**Comment by siddharthist** [comment]
@Zogg what's the status of this PR?

**Comment by siddharthist** [comment]
Closing this since it is out of sync and there haven't been any updates. Please reopen when this is ready to be merged!

**Pull request closed without merging**
