### PR TITLE
Added Design Philosophy

### PR DESCRIPTION
**Pull request by johnswil**
- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by sehqlr** [comment]
This supersedes #1636, right? We can close that PR in favor of this one?

**Comment by johnswil** [comment]
Correct, just did that.  Also, can you merge #1583?  Should be fine, not sure what the holdup is.

Thanks Sam ;-)

**Comment by stevendborrelli** [comment]
Somehow this doesn't seem like it should be part of the project's Readme page. Maybe this is something for the mantl.io site?

**Comment by siddharthist** [comment]
Seconded, the README should give people a very quick introduction to mantl, rather than a detailed background.

**Comment by johnswil** [comment]
Ok, the design philosophy is fairly brief and I feel fits within the quick introduction to Mantl, it also seems appropriate between goals and architecture.  It doesn't belong orphaned on Mantl.io.  Perhaps it should remain in FAQ's as originally committed for lack of a better home and "what's behind the design philosophy" makes some sense as a FAQ.  Thoughts?

**Comment by siddharthist** [comment]
I think (as I stated in the original PR) that this fits most neatly as another page in our documentation, linked to from the home page. That being said, I'd rather have it in the FAQ than in the README.

**Comment by siddharthist** [comment]
Closing since Steve and I don't think this is the right place. I'd love to see this in the docs, though!

**Pull request closed without merging**
