### PR TITLE
K8s/upgrade to 1.2.4

### PR DESCRIPTION
**Pull request by andreimc**
Upgrade k8s to latest stable

- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by andreimc** [comment]
This actually won't work on existing clusters, but is anyone using k8s yet as it's not fully supported ?

**Comment by stevendborrelli** [comment]
We're using it on some internal clusters for a development effort.

**Comment by andreimc** [comment]
Oh cool, so should the update be working like a rolling upgrade?

**Comment by siddharthist** [comment]
@andreimc There should always be a non-breaking upgrade path for people running the latest version of Mantl.

**Comment by andreimc** [comment]
@siddharthist cool thanks

**Pull request closed without merging**
