### PR TITLE
Add condition to check for definition of "provider"

### LINKED ISSUE #1056: lvm: provider not defined
When installing via bare metal (not terraform), the provider variable is not defined  for lvm tasks, causing an ansible error. 

https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/lvm/defaults/main.yml#L3

provider needs to be defined somewhere or we need to check if provider is defined in the template:

```
lvm_physical_device: "{% if provider == 'gce' %}/dev/disk/by-id/google-lvm{% elif provider == 'aws' %}/dev/xvdh{% elif provider == 'openstack' %}/dev/vdb{% endif %}"

```

### PR DESCRIPTION
**Pull request by siddharthist**
Fixes #1056

### CODE REVIEW

**Comment by ryane** [comment]
looks like there is an issue with the switch to multi-line syntax:

aws:


```
TASK: [lvm | Create volume group] ********************************************* 
failed: [mantl-ci-289-1-control-01] => {"failed": true}
msg: Device " /dev/xvdh " not found.
...
```

gce:

```
TASK: [lvm | Create volume group] ********************************************* 
failed: [mantl-ci-289-3-control-02] => {"failed": true}
msg: Device " /dev/disk/by-id/google-lvm " not found.
```

**Comment by siddharthist** [comment]
I just tried to fix it, but I'm having trouble testing on GCE, AWS, and OS :(

**Comment by siddharthist** [comment]
Looks like the whitespace issue is fixed, I'm unsure what's happening now:
```
msg: Device "/dev/xvdh" not found.
```
I'm going to try removing the quotes.

**Comment by siddharthist** [comment]
Looks like that did it! Build is passing on AWS.

**Comment by ryane** [comment]
+1 on GCE. lgtm

**Comment by siddharthist** [comment]
Thanks for testing @ryane, sorry for the oversights!

**Pull request merged**
