### PR TITLE
make dns and route53 names consistent with /etc/hosts

### PR DESCRIPTION
**Pull request by kbroughton**
This resolves https://github.com/CiscoCloud/mantl/issues/1277

- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by darKoram** [comment]
test this please

**Comment by siddharthist** [comment]
I'm a little confused - it doesn't look like the default options in this PR would be different from what they currently are. Would you mind explaining a bit more, @kbroughton?

**Comment by siddharthist** [comment]
@kbroughton Can you outline the acceptance criteria for testing this?

**Comment by kbroughton** [comment]
terraform apply
open route53 and view the server names.  eg.
https://drive.google.com/file/d/0B5bhZOuD4S4FLTRxLTduRU91blE/view?usp=sharing

ssh into any host.  
cat /etc/hosts

You should see that worker-001 is consistent in both locations.  Previously, /etc/hosts was worker-01

**Comment by kbroughton** [comment]
btw, i noticed that some of the other providers, openstack, cisco-os already have this mechanism.
I'm guessing gce will have the same issue as aws.  They even named the variable the same as me!

./terraform/openstack-modules.sample.tf:  count_format = "%03d"
./terraform/openstack-modules.sample.tf:  count_format = "%02d"
./testing/cisco-os.tf:  count_format = "%03d"
./testing/cisco-os.tf:  count_format = "%02d"

**Comment by kbroughton** [comment]
btw, i noticed that some of the other providers, openstack, cisco-os already have this mechanism.
I'm guessing gce will have the same issue as aws.  They even named the variable the same as me!

./terraform/openstack-modules.sample.tf:  count_format = "%03d"
./terraform/openstack-modules.sample.tf:  count_format = "%02d"
./testing/cisco-os.tf:  count_format = "%03d"
./testing/cisco-os.tf:  count_format = "%02d"

**Comment by siddharthist** [comment]
Testing now.

**Comment by siddharthist** [comment]
Works for me (AWS, obviously):
```
[centos@ip-10-1-1-199 ~]$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.1.3.64  lb1-control-03
10.1.3.34  lb1-worker-003
10.1.2.145  lb1-edge-02
10.1.1.65  lb1-edge-01
10.1.2.37  lb1-control-02
10.1.2.187  lb1-worker-002
10.1.1.199  lb1-control-01
10.1.1.169  lb1-worker-004
10.1.1.57  lb1-worker-001
```

**Pull request merged**
