### PR TITLE
use mantl 1.3 repo

### PR DESCRIPTION
**Pull request by ryane**
- [ ] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes (n/a)

---

WIP: not ready to merge. currently we get the following error:

`No Package matching 'distributive-0.2.5-1' found available, installed or updated`

We either need to push the `distributive-0.2.5-1` package into the repo or switch mantl to use distributive `0.3.0-1` but not sure of the status.

ping @siddharthist @Zogg

### CODE REVIEW

**Comment by siddharthist** [comment]
We should revert to distributive 0.2.5-1, there's an undiagnosed problem with 0.3.0

**Comment by siddharthist** [comment]
I've uploaded 0.2.5-1 into the new repo. We merge master and get a new CI build as soon as there's another commit :-)

**Comment by ryane** [comment]
consul-cli-0.1.1 is missing as well. 

`msg: No Package matching 'consul-cli-0.1.1' found available, installed or updated`

The latest version in the repo is 0.2.0-1 but 0.3.1 appears to be the latest release. @ChrisAubuchon   is there any reason not to push out a 0.3.1 package and update mantl to use it?

**Comment by ChrisAubuchon** [comment]
@ryane No reason that I can think of to not use 0.3.1.

**Comment by ryane** [comment]
ah and you already had a pr for that 👍

**Comment by ryane** [comment]
this is currently blocked by https://github.com/asteris-llc/mantl-packaging/issues/135

ping @avnik

**Comment by ryane** [comment]
@avnik any update on the traefik problem?

**Comment by ryane** [comment]
traefik package is fixed and latest test are all green. this should be ready for review/merge

**Comment by siddharthist** [comment]
Testing now

**Comment by siddharthist** [comment]
```
[root@lb-control-01 ~]# yum info consul-cli
Installed Packages
Name        : consul-cli
Arch        : x86_64
Version     : 0.3.1
Release     : 1
Size        : 11 M
Repo        : installed
From repo   : asteris-mantl-rpm
Summary     : Command line interface to Consul HTTP API
URL         : https://github.com/CiscoCloud/consul-cli
License     : APL 2.0
Description : Command line interface to Consul HTTP API
```
```
[root@lb-control-01 ~]# curl localhost:8500/v1/health/state/{warning,failing} 
[][][root@lb-control-01 ~]#
```

**Pull request merged**
