### PR TITLE
Fix/update packer

### PR DESCRIPTION
**Pull request by ChrisAubuchon**
Updates for v0.8 of the Vagrant box

### CODE REVIEW

**Comment by siddharthist** [comment]
I got an error, but it might be due to my incompetence with Packer rather than any changes. 
```
==> virtualbox-iso: Running post-processor: atlas
    virtualbox-iso (atlas): Creating artifact: /
Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Post-processor failed: Error creating artifact: resource not found

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: 1 error(s) occurred:

* Post-processor failed: Error creating artifact: resource not found

==> Builds finished but no artifacts were created.
```

**Comment by ChrisAubuchon** [comment]
This branch needs to be fast forwarded with master before building the packer image

**Comment by siddharthist** [comment]
I'm testing again, if it works, I'll push the rebase and merge this.

**Comment by siddharthist** [comment]
I get the same error when rebased onto current master.

**Comment by siddharthist** [comment]
I think @avnik is planning to improve our Packer process as described in #992. That might fix this problem and make this PR obsoltete.

**Pull request closed without merging**
