### PR TITLE
Integrate k8s with AWS

### PR DESCRIPTION
**Pull request by ryane**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

---

This allows kubernetes to manage things like ELBs and EBS volumes.

* enables cloud provider integration by default on aws
* adds iam profiles to control, worker, and kubeworker nodes
* adds KubernetesCluster tag to aws resources

_Note: if you do not clean up kubernetes-created resources (like elbs) in advance, terraform may not be able to destroy your cluster._

You can test the cloud integration by creating a Service with `type: LoadBalancer`. You can use the Kubernetes guestbook as an example. If you uncomment https://github.com/kubernetes/kubernetes/blob/master/examples/guestbook/all-in-one/guestbook-all-in-one.yaml#L130 and then run `kubectl create -f examples/guestbook/all-in-one/guestbook-all-in-one.yaml`, you should end up with an ELB exposing the guestbook app externally. You can get the ELB info by running `kubectl describe service frontend` or using the AWS UI/cli.

_Note: make sure to copy the changes in `terraform/aws.sample.tf` to your local `aws.tf` before testing._

### CODE REVIEW

**Comment by siddharthist** [comment]
Testing this now.

**Comment by siddharthist** [comment]
I got 
```
TASK: [kubernetes-master | wait for apiserver to come up] ********************* 
failed: [lb0-control-03] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for 127.0.0.1:8085
failed: [lb0-control-02] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for 127.0.0.1:8085
failed: [lb0-control-01] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for 127.0.0.1:8085
```

Investigating futher...

**Comment by ryane** [comment]
I am not able to repro this. Based on the error you received, it sounds like your nodes might not be getting the right IAM roles properly. Can you elaborate more on how you are doing your terraform setup?

**Comment by siddharthist** [comment]
@ryane It's just the file I posted in the comment above, in the project root directory. 
```
$ terraform version
Terraform v0.6.16
```
What other information would be helpful in particular?

**Comment by ryane** [comment]
what does your aws.tf look like?

**Comment by ryane** [comment]
(rebased)

**Comment by siddharthist** [comment]
Sure don't :/
```
+ module.aws-mantl.aws_instance.mi-worker-nodes.1
    ami:                                       "" => "ami-9bf712f4"
    associate_public_ip_address:               "" => "true"
    availability_zone:                         "" => "eu-central-1a"
    ebs_block_device.#:                        "" => "<computed>"
    ephemeral_block_device.#:                  "" => "<computed>"
    instance_state:                            "" => "<computed>"
    instance_type:                             "" => "m3.medium"
    key_name:                                  "" => "key-lb0"
    placement_group:                           "" => "<computed>"
    private_dns:                               "" => "<computed>"
    private_ip:                                "" => "<computed>"
    public_dns:                                "" => "<computed>"
    public_ip:                                 "" => "<computed>"
    root_block_device.#:                       "" => "1"
    root_block_device.0.delete_on_termination: "" => "true"
    root_block_device.0.iops:                  "" => "<computed>"
    root_block_device.0.volume_size:           "" => "20"
    root_block_device.0.volume_type:           "" => "<computed>"
    security_groups.#:                         "" => "<computed>"
    source_dest_check:                         "" => "true"
    subnet_id:                                 "" => "${aws_subnet.main.id}"
    tags.#:                                    "" => "4"
    tags.Name:                                 "" => "lb0-worker-002"
    tags.dc:                                   "" => "aws"
    tags.role:                                 "" => "worker"
    tags.sshUser:                              "" => "centos"
    tenancy:                                   "" => "<computed>"
    vpc_security_group_ids.#:                  "" => "<computed>"
```

```
+ module.aws-mantl.aws_instance.mi-control-nodes.1
    ami:                                       "" => "ami-9bf712f4"
    associate_public_ip_address:               "" => "true"
    availability_zone:                         "" => "eu-central-1a"
    ebs_block_device.#:                        "" => "<computed>"
    ephemeral_block_device.#:                  "" => "<computed>"
    instance_state:                            "" => "<computed>"
    instance_type:                             "" => "m3.medium"
    key_name:                                  "" => "key-lb0"
    placement_group:                           "" => "<computed>"
    private_dns:                               "" => "<computed>"
    private_ip:                                "" => "<computed>"
    public_dns:                                "" => "<computed>"
    public_ip:                                 "" => "<computed>"
    root_block_device.#:                       "" => "1"
    root_block_device.0.delete_on_termination: "" => "true"
    root_block_device.0.iops:                  "" => "<computed>"
    root_block_device.0.volume_size:           "" => "20"
    root_block_device.0.volume_type:           "" => "<computed>"
    security_groups.#:                         "" => "<computed>"
    source_dest_check:                         "" => "true"
    subnet_id:                                 "" => "${aws_subnet.main.id}"
    tags.#:                                    "" => "4"
    tags.Name:                                 "" => "lb0-control-02"
    tags.dc:                                   "" => "aws"
    tags.role:                                 "" => "control"
    tags.sshUser:                              "" => "centos"
    tenancy:                                   "" => "<computed>"
    vpc_security_group_ids.#:                  "" => "<computed>"
```

**Comment by ryane** [comment]
so yeah something appears to be different between our terraform setups. do you see 

```
+ module.iam-profiles.aws_iam_instance_profile.control_profile
...
+ module.iam-profiles.aws_iam_instance_profile.worker_profile
```

in your plan output?

 If you `cp terraform/aws.sample.tf ./aws.tf` do you see the right iam stuff? maybe run `terraform get` again?

**Comment by siddharthist** [comment]
@ryane Looks liek that works... maybe someone with a better aws config can test this. 
```
$ terraform plan | grep iam
+ module.iam-profiles.aws_iam_instance_profile.control_profile
+ module.iam-profiles.aws_iam_instance_profile.worker_profile
+ module.iam-profiles.aws_iam_role.control_role
+ module.iam-profiles.aws_iam_role.worker_role
+ module.iam-profiles.aws_iam_role_policy.control_policy
    role:   "" => "${aws_iam_role.control_role.id}"
+ module.iam-profiles.aws_iam_role_policy.worker_policy
    role:   "" => "${aws_iam_role.worker_role.id}"
    iam_instance_profile:                      "" => "worker_profile"
    iam_instance_profile:                      "" => "worker_profile"
    iam_instance_profile:                      "" => "worker_profile"
    iam_instance_profile:                      "" => "worker_profile"
    iam_instance_profile:                      "" => "worker_profile"
    iam_instance_profile:                      "" => "worker_profile"
    iam_instance_profile:                      "" => "control_profile"
    iam_instance_profile:                      "" => "control_profile"
    iam_instance_profile:                      "" => "control_profile"
```

**Comment by ryane** [comment]
it looks like the problem was due to the use of the legacy aws terraform which did not have the iam support added. I added it and hopefully this will work now for CI (aws passed) and for anyone not using the aws terraform modules.

see #1692 and #1693

**Comment by siddharthist** [comment]
Testing now with a newer TF config.

**Comment by ryane** [comment]
@sehqlr would you be able to give this a test?

**Comment by siddharthist** [comment]
Got a fresh aws.sample.tf, attempting to test now.

**Comment by siddharthist** [comment]
Tests passed with guestbook example:
```
[centos@mantl-control-03 ~]$ kubectl describe service frontend                       
Name:			frontend
Namespace:		kube-system
Labels:			app=guestbook,tier=frontend
Selector:		app=guestbook,tier=frontend
Type:			LoadBalancer
IP:			10.254.201.187
LoadBalancer Ingress:	a8e68d3f24d9611e6b1a60a72eea6d2f-941030701.us-west-2.elb.amazonaws.com
Port:			<unset>	80/TCP
NodePort:		<unset>	30646/TCP
Endpoints:		192.168.1.66:80,192.168.1.67:80
Session Affinity:	None
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type	Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1m		1m		1	{service-controller }			NormalCreatingLoadBalancer	Creating load balancer
  1m		1m		1	{service-controller }			NormalCreatedLoadBalancer	Created load balancer
```

**Pull request merged**
