### PR TITLE
Kubernetes by default

### PR DESCRIPTION
**Pull request by BrianHicks**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

Add Kubernetes by default, incorporating many of @zogg's changes. Docs are at https://github.com/CiscoCloud/mantl/commit/3af143e112777648da642a370bff4590fa48604c

Successor to #1302, obsoletes #1121 (since we no longer have to customize those variables)

### CODE REVIEW

**Comment by BrianHicks** [comment]
Just rebased onto lastest master.

**Comment by siddharthist** [comment]
After rebasing onto #1296, this upgrades cleanly from 1.0.3 :+1:

**Comment by siddharthist** [comment]
@BrianHicks is this ready to merge now that we know it upgrades cleanly?

**Comment by BrianHicks** [comment]
I thought it was, but it looks like Kubelet is killing the `logstash` and `nginx-consul` containers on the box when it starts up. This leads to an unhealthy status in Consul (because of the dsitributive check.)

I think it's going to require a few changes to nginx-consul and logstash (specifically to restart them when they fail), which may fall outside the scope of this PR. @ryane do you have a preference for where that should go?

**Comment by BrianHicks** [comment]
I added it in 48d0058, but we can revert that commit.

**Comment by ryane** [comment]
I suppose we could move it to a new PR but I don't have a problem with leaving it in this one...

**Comment by BrianHicks** [comment]
Cool, then it's ready to merge

**Pull request merged**
