### PR TITLE
Hardcode consul_dns_domain

### LINKED ISSUE #1252: Hardcode consul_dns_domain as ".consul"
Per discussion on #1246, to simplify our configuration we're going to remove `consul_dns_domain`. This won't have a huge effect on users, as everyone should pretty much be using `.consul`. #1246 makes it possible to leave off the TLD, however, so even users who did customize should move to the new setting.

### PR DESCRIPTION
**Pull request by siddharthist**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release ???
- [x] Updates documentation relevant to the changes

Also includes the changes of #1448, so will obsolete that if merged. 

Fixes #1252

### CODE REVIEW

**Comment by siddharthist** [comment]
I'm not sure about the test failure, this should probably be manually tested on DO.

**Comment by ryane** [comment]
I haven't tested this but is this going to work with the mantl-dns changes that addressed #1447? For example, on a 1.1 cluster, I cannot resolve names without the `.consul` suffix:

```
$ host etcd.service
Host etcd.service not found: 3(NXDOMAIN)
$ host etcd.service.consul
etcd.service.consul has address 10.1.2.238
etcd.service.consul has address 10.1.2.138
etcd.service.consul has address 10.1.1.65
$ host resching-aws-control-01.node
Host resching-aws-control-01.node not found: 3(NXDOMAIN)
$ host resching-aws-control-01.node.consul
resching-aws-control-01.node.consul has address 10.1.1.171
```

**Comment by siddharthist** [comment]
@ryane Of course you're totally right, instead of removing it from all these places, we just need to hardcode it.

**Comment by siddharthist** [comment]
This is ready for review again

**Comment by siddharthist** [comment]
This has been integrated with the new Mesos/K8s/Calico PR and is ready for review again

**Comment by ryane** [comment]
gce build passed, do and aws builds failed due to timeouts. manually tested on aws without any problems. lgtm

**Comment by siddharthist** [comment]
@ryane Thanks for merging!

**Pull request merged**
