### PR TITLE
Vagrant update to include Kube worker

### PR DESCRIPTION
**Pull request by andreimc**
#1365 was the original PR opened of a branch

- [ n/a] Installs cleanly on a fresh build of most recent master branch
- [n/a ] Upgrades cleanly from the most recent release
- [ na] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by siddharthist** [comment]
@andreimc Is this ready to test, or does it still have issues?

**Comment by andreimc** [comment]
@siddharthist I will double check today

**Comment by andreimc** [comment]
@siddharthist this worked well this time around. It should be ready to test

**Comment by siddharthist** [comment]
@andreimc Yay! @sehqlr could you test this?

**Comment by sehqlr** [comment]
I was able to get green on this.

**Comment by siddharthist** [comment]
Thanks for all your hard work, @andreimc! It's awesome to finally get this in :smile:

**Pull request merged**
