### PR TITLE
update kubelet hostname override

### PR DESCRIPTION
**Pull request by ryane**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

This or #1374 is sufficient to fix at least one of the problems in #1367 but both together is probably better.

### CODE REVIEW

**Comment by BrianHicks** [comment]
Did you just not mark the "upgrade" because you're not sure? Because it looks like that'd upgrade just fine to me.

**Comment by ryane** [comment]
Yeah, I tend to only mark it if I actually tested it but that's probably not sustainable. I agree, it looks like it will upgrade ok

**Comment by andreimc** [comment]
@ryane I will test this fix on vagrant later today let you know if it fixes the issue

**Comment by andreimc** [comment]
@ryane  still getting 502 with this merged in.
screen shot 2016-04-23 at 12 19 10 pm

**Comment by andreimc** [comment]
I get the following 

TASK: [kubernetes-addons | create or update dashboard] ************************
failed: [control-01] => {"failed": true}
msg: error running kubectl (/bin/kubectl --server=http://localhost:8085/ --namespace=kube-system create --filename=/etc/kubernetes/manifests/kubernetes-dashboard.yaml) command (rc=1): replicationcontroller "kubernetes-dashboard" created


FATAL: all hosts have already failed -- aborting

**Comment by sehqlr** [comment]
I tested this on AWS and Vagrant. LGTM

**Comment by distributorofpain** [comment]
Not sure if this is related, but i just deployed a fresh deployment to Digital Ocean ( no errors ).  Freshly built command server with latest centos 7.2 image.  Consul shows kubernetes all green, but when i try to launch the UI i get 404 not found from nginx/1.6.2 .  All other aspects of mantl are working properly.

**Pull request merged**
