### PR TITLE
lvm: fix parsing values of absolute amounts for volumes

### PR DESCRIPTION
**Pull request by avnik**
This fix also is a candidate to stable branch 1.2

- [x] Installs cleanly on a fresh build of most recent master branch
- [ ] Upgrades cleanly from the most recent release
- [ ] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by avnik** [comment]
Also should be tested with `-e debug_storage_setup=True`

**Comment by siddharthist** [comment]
@avnik What are the testing criteria? Do we have to change a default variable so that the new code is tested (besides `debug_storage_setup`)?

**Comment by avnik** [comment]
On Thu, Jul 14, 2016 at 03:09:44AM -0700, Langston Barrett wrote:

> @avnik What are the testing criteria? Do we have to change a default variable so that the new code is tested (besides `debug_storage_setup`)?
> 

Testing critria is seting  docker volume for _absolute_ size:  `docker_lvm_data_volume_size: 15G` for example.
This fix make it works.

`debug_storage_setup` only force scripts from repo, instead of RPM. I'll update RPM asap, when testing will be done.

**Comment by siddharthist** [comment]
I got an error. Here's my config:
```
mantl > cat roles/docker/defaults/main.yml | grep data_volume_size
docker_lvm_data_volume_size: 10G
docker_lvm_data_volume_size_min: 2G
docker_volume_size: "{{ docker_lvm_data_volume_size }}"
```
And the message:
```
TASK: [docker | process with mantl storage setup] ***************************** 
failed: [lb0-worker-002] => {"changed": true, "cmd": "/usr/bin/mantl-storage-setup", "delta": "0:00:00.176288", "end": "2016-07-15 10:04:21.784482", "rc": 1, "start": "2016-07-15 10:04:21.608194", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/bin/mantl-storage-setup", line 296, in <module>
    main()
  File "/usr/bin/mantl-storage-setup", line 289, in main
    iterate_config("volume", process_volume, cp)
  File "/usr/bin/mantl-storage-setup", line 277, in iterate_config
    fun(each, cp)
  File "/usr/bin/mantl-storage-setup", line 147, in process_volume
    size, size_opt, size_unit = parse_size(size)
  File "/usr/bin/mantl-storage-setup", line 135, in parse_size
    return int(m.group(1)), "L", m.group(2)
IndexError: no such group
stdout:   Physical volume "/dev/xvdh" successfully created
  Volume group "mantl" successfully created
==> Processing: /etc/mantl/filesystems.d/10-volume-group.conf
READ:  ['/sbin/pvs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'pv_all,vg_name', '--separator', ';']
READ:  ['/sbin/vgs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'all', '--separator', ';']
==> Processing: /etc/mantl/filesystems.d/20-docker-volume.conf
failed: [lb0-control-03] => {"changed": true, "cmd": "/usr/bin/mantl-storage-setup", "delta": "0:00:00.162313", "end": "2016-07-15 10:04:21.783770", "rc": 1, "start": "2016-07-15 10:04:21.621457", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/bin/mantl-storage-setup", line 296, in <module>
    main()
  File "/usr/bin/mantl-storage-setup", line 289, in main
    iterate_config("volume", process_volume, cp)
  File "/usr/bin/mantl-storage-setup", line 277, in iterate_config
    fun(each, cp)
  File "/usr/bin/mantl-storage-setup", line 147, in process_volume
    size, size_opt, size_unit = parse_size(size)
  File "/usr/bin/mantl-storage-setup", line 135, in parse_size
    return int(m.group(1)), "L", m.group(2)
IndexError: no such group
stdout:   Physical volume "/dev/xvdh" successfully created
  Volume group "mantl" successfully created
==> Processing: /etc/mantl/filesystems.d/10-volume-group.conf
READ:  ['/sbin/pvs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'pv_all,vg_name', '--separator', ';']
READ:  ['/sbin/vgs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'all', '--separator', ';']
==> Processing: /etc/mantl/filesystems.d/20-docker-volume.conf
failed: [lb0-control-02] => {"changed": true, "cmd": "/usr/bin/mantl-storage-setup", "delta": "0:00:00.158287", "end": "2016-07-15 10:04:21.789124", "rc": 1, "start": "2016-07-15 10:04:21.630837", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/bin/mantl-storage-setup", line 296, in <module>
    main()
  File "/usr/bin/mantl-storage-setup", line 289, in main
    iterate_config("volume", process_volume, cp)
  File "/usr/bin/mantl-storage-setup", line 277, in iterate_config
    fun(each, cp)
  File "/usr/bin/mantl-storage-setup", line 147, in process_volume
    size, size_opt, size_unit = parse_size(size)
  File "/usr/bin/mantl-storage-setup", line 135, in parse_size
    return int(m.group(1)), "L", m.group(2)
IndexError: no such group
stdout:   Physical volume "/dev/xvdh" successfully created
  Volume group "mantl" successfully created
==> Processing: /etc/mantl/filesystems.d/10-volume-group.conf
READ:  ['/sbin/pvs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'pv_all,vg_name', '--separator', ';']
READ:  ['/sbin/vgs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'all', '--separator', ';']
==> Processing: /etc/mantl/filesystems.d/20-docker-volume.conf
failed: [lb0-edge-01] => {"changed": true, "cmd": "/usr/bin/mantl-storage-setup", "delta": "0:00:00.153066", "end": "2016-07-15 10:04:21.939292", "rc": 1, "start": "2016-07-15 10:04:21.786226", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/bin/mantl-storage-setup", line 296, in <module>
    main()
  File "/usr/bin/mantl-storage-setup", line 289, in main
    iterate_config("volume", process_volume, cp)
  File "/usr/bin/mantl-storage-setup", line 277, in iterate_config
    fun(each, cp)
  File "/usr/bin/mantl-storage-setup", line 147, in process_volume
    size, size_opt, size_unit = parse_size(size)
  File "/usr/bin/mantl-storage-setup", line 135, in parse_size
    return int(m.group(1)), "L", m.group(2)
IndexError: no such group
stdout:   Physical volume "/dev/xvdh" successfully created
  Volume group "mantl" successfully created
==> Processing: /etc/mantl/filesystems.d/10-volume-group.conf
READ:  ['/sbin/pvs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'pv_all,vg_name', '--separator', ';']
READ:  ['/sbin/vgs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'all', '--separator', ';']
==> Processing: /etc/mantl/filesystems.d/20-docker-volume.conf
failed: [lb0-control-01] => {"changed": true, "cmd": "/usr/bin/mantl-storage-setup", "delta": "0:00:00.172491", "end": "2016-07-15 10:04:22.003993", "rc": 1, "start": "2016-07-15 10:04:21.831502", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/bin/mantl-storage-setup", line 296, in <module>
    main()
  File "/usr/bin/mantl-storage-setup", line 289, in main
    iterate_config("volume", process_volume, cp)
  File "/usr/bin/mantl-storage-setup", line 277, in iterate_config
    fun(each, cp)
  File "/usr/bin/mantl-storage-setup", line 147, in process_volume
    size, size_opt, size_unit = parse_size(size)
  File "/usr/bin/mantl-storage-setup", line 135, in parse_size
    return int(m.group(1)), "L", m.group(2)
IndexError: no such group
stdout:   Physical volume "/dev/xvdh" successfully created
  Volume group "mantl" successfully created
==> Processing: /etc/mantl/filesystems.d/10-volume-group.conf
READ:  ['/sbin/pvs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'pv_all,vg_name', '--separator', ';']
READ:  ['/sbin/vgs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'all', '--separator', ';']
==> Processing: /etc/mantl/filesystems.d/20-docker-volume.conf
failed: [lb0-kubeworker-001] => {"changed": true, "cmd": "/usr/bin/mantl-storage-setup", "delta": "0:00:00.214339", "end": "2016-07-15 10:04:22.038969", "rc": 1, "start": "2016-07-15 10:04:21.824630", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/bin/mantl-storage-setup", line 296, in <module>
    main()
  File "/usr/bin/mantl-storage-setup", line 289, in main
    iterate_config("volume", process_volume, cp)
  File "/usr/bin/mantl-storage-setup", line 277, in iterate_config
    fun(each, cp)
  File "/usr/bin/mantl-storage-setup", line 147, in process_volume
    size, size_opt, size_unit = parse_size(size)
  File "/usr/bin/mantl-storage-setup", line 135, in parse_size
    return int(m.group(1)), "L", m.group(2)
IndexError: no such group
stdout:   Physical volume "/dev/xvdh" successfully created
  Volume group "mantl" successfully created
==> Processing: /etc/mantl/filesystems.d/10-volume-group.conf
READ:  ['/sbin/pvs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'pv_all,vg_name', '--separator', ';']
READ:  ['/sbin/vgs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'all', '--separator', ';']
==> Processing: /etc/mantl/filesystems.d/20-docker-volume.conf
failed: [lb0-worker-001] => {"changed": true, "cmd": "/usr/bin/mantl-storage-setup", "delta": "0:00:00.215793", "end": "2016-07-15 10:04:22.100355", "rc": 1, "start": "2016-07-15 10:04:21.884562", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/bin/mantl-storage-setup", line 296, in <module>
    main()
  File "/usr/bin/mantl-storage-setup", line 289, in main
    iterate_config("volume", process_volume, cp)
  File "/usr/bin/mantl-storage-setup", line 277, in iterate_config
    fun(each, cp)
  File "/usr/bin/mantl-storage-setup", line 147, in process_volume
    size, size_opt, size_unit = parse_size(size)
  File "/usr/bin/mantl-storage-setup", line 135, in parse_size
    return int(m.group(1)), "L", m.group(2)
IndexError: no such group
stdout:   Physical volume "/dev/xvdh" successfully created
  Volume group "mantl" successfully created
==> Processing: /etc/mantl/filesystems.d/10-volume-group.conf
READ:  ['/sbin/pvs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'pv_all,vg_name', '--separator', ';']
READ:  ['/sbin/vgs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'all', '--separator', ';']
==> Processing: /etc/mantl/filesystems.d/20-docker-volume.conf
```

**Comment by ryane** [comment]
@siddharthist hm, this worked for me. Any idea what might be different? did you definitely run with `debug_storage_setup=True`?

```diff
diff --git a/roles/docker/defaults/main.yml b/roles/docker/defaults/main.yml
index 9255889..6a1da3a 100644
--- a/roles/docker/defaults/main.yml
+++ b/roles/docker/defaults/main.yml
@@ -43,7 +43,7 @@ docker_storage_driver: overlay
 ## These are not used for overlay on lvm
 ## Refer to commentaries in ../templates/docker-storage-setup.conf.j2
 ## or `man lvcreate` for acceptable sizes, and their syntax
-docker_lvm_data_volume_size: 40%FREE
+docker_lvm_data_volume_size: 10G
 docker_lvm_data_volume_size_min: 2G

 docker_lvm_auto_extend_pool: yes
diff --git a/roles/lvm/defaults/main.yml b/roles/lvm/defaults/main.yml
index ceba16a..868d625 100644
--- a/roles/lvm/defaults/main.yml
+++ b/roles/lvm/defaults/main.yml
@@ -7,4 +7,4 @@ lvm_physical_device: >
   {%- elif provider == 'openstack' -%}/dev/vdb
   {%- endif -%}{%- endif -%}

-debug_storage_setup: False
+debug_storage_setup: True
```

```shell
$ sudo lvdisplay
  --- Logical volume ---
  LV Path                /dev/mantl/docker
  LV Name                docker
  VG Name                mantl
  LV UUID                uD85jX-F3nq-PWmF-t9cA-GHcy-fhh3-aGFgKl
  LV Write Access        read/write
  LV Creation host, time ip-10-1-2-163.ec2.internal, 2016-07-15 15:11:37 +0000
  LV Status              available
  # open                 1
  LV Size                10.00 GiB
  Current LE             2560
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     8192
  Block device           253:0

$ sudo pvdisplay
  --- Physical volume ---
  PV Name               /dev/xvdh
  VG Name               mantl
  PV Size               100.00 GiB / not usable 4.00 MiB
  Allocatable           yes
  PE Size               4.00 MiB
  Total PE              25599
  Free PE               23039
  Allocated PE          2560
  PV UUID               hAEfnv-HeQf-IDY1-CJrS-RFIc-Yamx-8rfe27
```

**Comment by siddharthist** [comment]
Oh, I thought it had to be tested with both `debug_storage_setup=True` and `debug_storage_setup=False`. This works for me with `debug_storage_setup=True`. :+1:

**Comment by ryane** [comment]
@avnik it looks like this works - can you update the rpm (and this pr if needed) with the updated mantl-storage-setup so that it will work without setting `debug_storage_setup=True`?

**Comment by avnik** [comment]
@ryan sure. I merge it now. And fix RPM today

**Pull request merged**
