### PR TITLE
Change default vpc name to mantl

### PR DESCRIPTION
**Pull request by siddharthist**
- [x] Installs cleanly on a fresh build of most recent master branch
- [x] Upgrades cleanly from the most recent release
- [x] Updates documentation relevant to the changes

### CODE REVIEW

**Comment by ryane** [comment]
can we expose the `long_name` var in aws.sample.tf so that it can be customized? (like we do in gce.sample.tf, for example)

**Comment by siddharthist** [comment]
@ryane Is that what you had in mind?

**Comment by ryane** [comment]
yes, that way the vpc name can be set to something other than `mantl`. Another question is whether we actually need a `long_name` and a `short_name` but this lgtm for now.

**Comment by ryane** [comment]
verified I could customize vpc name and aws build passed.

**Pull request merged**
